/*****************************************************************************
    Verilog RTL Simulation Model
    
    Generated at: 23:06:39 EDT (-0400), Thursday 04 August 2016
    Generated on: zhang-01.ece.cornell.edu
    Generated by: yw777 (You Wu)
    
    Created by: Cynthesizer DpOpt 2015.1.01 
    Copyright (c) 2014-2015 Cadence Design Systems. All rights reserved worldwide.
    
    Cadence Design Systems proprietary and confidential
    ===================================================
    
    May contain information that incorporates Cadence Design Systems CellMath
    and other inventions claimed in Pending U.S. Patents.
    
    May contain Cadence Design Systems Trade Secrets of which use, disclosure or
    reproduction is contractually restricted or prohibited.  For more
    information, contact your legal department before any use, disclosure or
    reproduction.
*******************************************************************************/

module vv_add_DECODE_16U_8_4 (
	in1,
	out1
	); /* architecture "behavioural" */ 
input [3:0] in1;
output [15:0] out1;
wire [15:0] asc001;

assign asc001 = 16'B0000000000000001 << in1;

assign out1 = asc001;
endmodule

/* CADENCE  ubD1Tg4= : u9/ySgnatBlWxVPRUQkd5eg= ** DO NOT EDIT THIS LINE ******/

