// Generated by stratus_hls 15.21-p100  (11111647)
// Thu Aug  4 23:07:52 2016
// from vv_add.cc
#ifndef CYNTH_PART_vv_add_vv_add_rtl_h
#define CYNTH_PART_vv_add_vv_add_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct vv_add : public sc_module {
  sc_in<bool > clk;
  sc_in<bool > rst;
  sc_out<bool > cc_busy_o;
  sc_out<bool > cc_interrupt_o;
  sc_in<bool > cc_status_i;
  sc_in<bool > cc_exception_i;
  sc_in<bool > cc_host_id_i;
  sc_out<bool > core_cmd_ready_o;
  sc_in<bool > core_cmd_valid_i;
  sc_in<sc_uint<7> > core_cmd_inst_funct_i;
  sc_in<sc_uint<5> > core_cmd_inst_rs1_i;
  sc_in<sc_uint<5> > core_cmd_inst_rs2_i;
  sc_in<bool > core_cmd_inst_xd_i;
  sc_in<bool > core_cmd_inst_xs1_i;
  sc_in<bool > core_cmd_inst_xs2_i;
  sc_in<sc_uint<5> > core_cmd_inst_rd_i;
  sc_in<sc_uint<7> > core_cmd_inst_opcode_i;
  sc_in<sc_uint<64> > core_cmd_rs1_i;
  sc_in<sc_uint<64> > core_cmd_rs2_i;
  sc_in<bool > core_resp_ready_i;
  sc_out<bool > core_resp_valid_o;
  sc_out<sc_uint<5> > core_resp_rd_o;
  sc_out<sc_uint<64> > core_resp_data_o;
  sc_in<bool > mem_req_ready_i;
  sc_out<bool > mem_req_valid_o;
  sc_out<sc_uint<40> > mem_req_addr_o;
  sc_out<sc_uint<10> > mem_req_tag_o;
  sc_out<sc_uint<5> > mem_req_cmd_o;
  sc_out<sc_uint<3> > mem_req_typ_o;
  sc_out<bool > mem_req_phys_o;
  sc_out<sc_uint<64> > mem_req_data_o;
  sc_in<bool > mem_resp_valid_i;
  sc_in<sc_uint<40> > mem_resp_addr_i;
  sc_in<sc_uint<10> > mem_resp_tag_i;
  sc_in<sc_uint<5> > mem_resp_cmd_i;
  sc_in<sc_uint<3> > mem_resp_typ_i;
  sc_in<sc_uint<64> > mem_resp_data_i;
  sc_in<bool > mem_resp_has_data_i;
  sc_in<sc_uint<64> > mem_resp_data_word_bypass_i;
  sc_in<sc_uint<64> > mem_resp_store_data_i;
  sc_in<bool > mem_resp_nack_i;
  sc_in<bool > mem_resp_replay_i;
  vv_add( sc_module_name name );
  SC_HAS_PROCESS(vv_add);
  sc_signal<sc_uint<4> > global_state_next;
  sc_signal<sc_uint<1> > vv_add_And_1U_0_4_5_out1;
  sc_signal<sc_uint<1> > vv_add_Eqi3u10_4_4_out1;
  sc_signal<sc_uint<1> > vv_add_And_1U_0_4_3_out1;
  sc_signal<sc_uint<1> > vv_add_Eqi2u10_4_2_out1;
  sc_signal<sc_uint<64> > s_reg_18;
  sc_signal<sc_uint<5> > s_reg_17;
  sc_signal<sc_uint<64> > vv_add_Add_64U_3_4_1_out1;
  sc_signal<sc_uint<64> > s_reg_12;
  sc_signal<sc_uint<1> > s_reg_14;
  sc_signal<sc_uint<64> > s_reg_16;
  sc_signal<sc_uint<2> > mem_req_tag_o_slice;
  sc_signal<sc_uint<1> > mem_req_cmd_o_slice;
  sc_signal<sc_uint<1> > mem_req_typ_o_slice;
  sc_signal<sc_uint<64> > s_reg_15;
  sc_signal<sc_uint<7> > s_reg_13;
  sc_signal<sc_uint<4> > global_state;
  void drive_mem_req_data_o();
  void drive_mem_req_typ_o();
  void drive_mem_req_cmd_o();
  void drive_mem_req_tag_o();
  void drive_mem_req_addr_o();
  void drive_mem_req_valid_o();
  void drive_core_resp_data_o();
  void drive_core_resp_rd_o();
  void drive_core_resp_valid_o();
  void drive_core_cmd_ready_o();
  void drive_cc_busy_o();
  void drive_s_reg_12();
  void drive_s_reg_13();
  void drive_s_reg_14();
  void drive_s_reg_15();
  void drive_s_reg_16();
  void drive_s_reg_17();
  void drive_s_reg_18();
  void vv_add_Add_64U_3_4_1();
  void vv_add_Eqi2u10_4_2();
  void vv_add_And_1U_0_4_3();
  void vv_add_Eqi3u10_4_4();
  void vv_add_And_1U_0_4_5();
  void drive_global_state();
  void drive_global_state_next();
  void thread_12();
  void thread_11();
  void thread_10();
  void thread_9();
  void thread_8();
};

#endif
