`timescale 1ps / 1ps
/*****************************************************************************
    Verilog RTL Simulation Model
    
    Generated at: 11:19:54 EDT (-0400), Friday 22 July 2016
    Generated on: zhang-01.ece.cornell.edu
    Generated by: yw777 (You Wu)
    
    Created by: Cynthesizer DpOpt 2015.1.01 
    Copyright (c) 2014-2015 Cadence Design Systems. All rights reserved worldwide.
    
    Cadence Design Systems proprietary and confidential
    ===================================================
    
    May contain information that incorporates Cadence Design Systems CellMath
    and other inventions claimed in Pending U.S. Patents.
    
    May contain Cadence Design Systems Trade Secrets of which use, disclosure or
    reproduction is contractually restricted or prohibited.  For more
    information, contact your legal department before any use, disclosure or
    reproduction.
*******************************************************************************/

module RAM_N_Muxb_1_2_13_4 (
	in3,
	in2,
	ctrl1,
	out1
	); /* architecture "behavioural" */ 
input  in3,
	in2,
	ctrl1;
output  out1;
wire  asc001;

reg [0:0] asc001_tmp_0;
assign asc001 = asc001_tmp_0;
always @ (ctrl1 or in2 or in3) begin
	case (ctrl1)
		1'B1 : asc001_tmp_0 = in2 ;
		default : asc001_tmp_0 = in3 ;
	endcase
end

assign out1 = asc001;
endmodule

/* CADENCE  uLH1SQg= : u9/ySgnatBlWxVPRUQkd5eg= ** DO NOT EDIT THIS LINE ******/


