`timescale 1ps / 1ps
/*****************************************************************************
    Verilog RTL Simulation Model
    
    Generated at: 14:11:53 EDT (-0400), Friday 22 July 2016
    Generated on: zhang-01.ece.cornell.edu
    Generated by: yw777 (You Wu)
    
    Created by: Cynthesizer DpOpt 2015.1.01 
    Copyright (c) 2014-2015 Cadence Design Systems. All rights reserved worldwide.
    
    Cadence Design Systems proprietary and confidential
    ===================================================
    
    May contain information that incorporates Cadence Design Systems CellMath
    and other inventions claimed in Pending U.S. Patents.
    
    May contain Cadence Design Systems Trade Secrets of which use, disclosure or
    reproduction is contractually restricted or prohibited.  For more
    information, contact your legal department before any use, disclosure or
    reproduction.
*******************************************************************************/

module RAM_Mul2i7u9_4 (
	in1,
	out1
	); /* architecture "behavioural" */ 
input [8:0] in1;
output [8:0] out1;
wire [8:0] asc001;

assign asc001 = 
	+(in1 * 9'B000000111);

assign out1 = asc001;
endmodule

/* CADENCE  urf0SAA= : u9/ySgnatBlWxVPRUQkd5eg= ** DO NOT EDIT THIS LINE ******/


