`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Add_7Sx2S_8S_4(in2, in1, out1);
  input [6:0] in2;
  input [1:0] in1;
  output [7:0] out1;
  wire [6:0] in2;
  wire [1:0] in1;
  wire [7:0] out1;
  wire add_35_2_n_0, add_35_2_n_2, add_35_2_n_4, add_35_2_n_6,
       add_35_2_n_8, add_35_2_n_10, add_35_2_n_12, add_35_2_n_14;
  INVX1 add_35_2_g206(.A (add_35_2_n_14), .Y (out1[6]));
  ADDFX1 add_35_2_g207(.A (add_35_2_n_12), .B (in1[1]), .CI (in2[6]),
       .CO (out1[7]), .S (add_35_2_n_14));
  INVX1 add_35_2_g208(.A (add_35_2_n_10), .Y (add_35_2_n_12));
  ADDFX1 add_35_2_g209(.A (add_35_2_n_8), .B (in1[1]), .CI (in2[5]),
       .CO (add_35_2_n_10), .S (out1[5]));
  ADDFX1 add_35_2_g210(.A (add_35_2_n_6), .B (in1[1]), .CI (in2[4]),
       .CO (add_35_2_n_8), .S (out1[4]));
  ADDFX1 add_35_2_g211(.A (add_35_2_n_4), .B (in1[1]), .CI (in2[3]),
       .CO (add_35_2_n_6), .S (out1[3]));
  ADDFX1 add_35_2_g212(.A (add_35_2_n_2), .B (in1[1]), .CI (in2[2]),
       .CO (add_35_2_n_4), .S (out1[2]));
  ADDFX1 add_35_2_g213(.A (add_35_2_n_0), .B (in1[1]), .CI (in2[1]),
       .CO (add_35_2_n_2), .S (out1[1]));
  ADDHX1 add_35_2_g214(.A (in2[0]), .B (in1[0]), .CO (add_35_2_n_0), .S
       (out1[0]));
endmodule


