`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Add_7Sx2S_8S_1(in2, in1, out1);
  input [6:0] in2;
  input [1:0] in1;
  output [7:0] out1;
  wire [6:0] in2;
  wire [1:0] in1;
  wire [7:0] out1;
  wire add_35_2_n_5, add_35_2_n_6, add_35_2_n_7, add_35_2_n_8,
       add_35_2_n_9, add_35_2_n_10, add_35_2_n_11, add_35_2_n_13;
  wire add_35_2_n_14, add_35_2_n_15, add_35_2_n_16, add_35_2_n_17,
       add_35_2_n_18, add_35_2_n_19, add_35_2_n_20, add_35_2_n_21;
  wire add_35_2_n_22, add_35_2_n_23, add_35_2_n_24, add_35_2_n_25,
       add_35_2_n_26, add_35_2_n_27, add_35_2_n_28, add_35_2_n_29;
  wire add_35_2_n_30, add_35_2_n_31, add_35_2_n_32, add_35_2_n_33,
       add_35_2_n_34, add_35_2_n_35, add_35_2_n_36, add_35_2_n_37;
  wire add_35_2_n_38, add_35_2_n_39, n_52, n_53;
  MXI2XL add_35_2_g142(.A (add_35_2_n_29), .B (add_35_2_n_28), .S0
       (add_35_2_n_39), .Y (out1[6]));
  MXI2XL add_35_2_g143(.A (add_35_2_n_26), .B (add_35_2_n_25), .S0
       (add_35_2_n_38), .Y (out1[5]));
  AOI21X1 add_35_2_g144(.A0 (add_35_2_n_32), .A1 (add_35_2_n_36), .B0
       (add_35_2_n_35), .Y (out1[7]));
  AOI21X1 add_35_2_g145(.A0 (add_35_2_n_27), .A1 (add_35_2_n_36), .B0
       (add_35_2_n_31), .Y (add_35_2_n_39));
  AOI21X1 add_35_2_g146(.A0 (add_35_2_n_18), .A1 (add_35_2_n_36), .B0
       (add_35_2_n_10), .Y (add_35_2_n_38));
  OAI21X1 add_35_2_g149(.A0 (add_35_2_n_11), .A1 (add_35_2_n_34), .B0
       (n_52), .Y (add_35_2_n_37));
  OAI21X2 add_35_2_g151(.A0 (add_35_2_n_21), .A1 (add_35_2_n_34), .B0
       (add_35_2_n_30), .Y (add_35_2_n_36));
  OAI2BB1X1 add_35_2_g152(.A0N (add_35_2_n_7), .A1N (add_35_2_n_31),
       .B0 (add_35_2_n_13), .Y (add_35_2_n_35));
  NOR2X2 add_35_2_g153(.A (add_35_2_n_8), .B (add_35_2_n_33), .Y
       (add_35_2_n_34));
  NOR2X2 add_35_2_g155(.A (add_35_2_n_16), .B (add_35_2_n_5), .Y
       (add_35_2_n_33));
  AND2XL add_35_2_g156(.A (add_35_2_n_7), .B (add_35_2_n_27), .Y
       (add_35_2_n_32));
  OAI21X1 add_35_2_g157(.A0 (add_35_2_n_9), .A1 (add_35_2_n_19), .B0
       (add_35_2_n_15), .Y (add_35_2_n_31));
  OA21X1 add_35_2_g158(.A0 (n_53), .A1 (add_35_2_n_6), .B0
       (add_35_2_n_14), .Y (add_35_2_n_30));
  INVX1 add_35_2_g160(.A (add_35_2_n_28), .Y (add_35_2_n_29));
  NAND2X1 add_35_2_g161(.A (add_35_2_n_7), .B (add_35_2_n_13), .Y
       (add_35_2_n_28));
  NOR2X1 add_35_2_g162(.A (add_35_2_n_19), .B (add_35_2_n_17), .Y
       (add_35_2_n_27));
  INVX1 add_35_2_g163(.A (add_35_2_n_25), .Y (add_35_2_n_26));
  NAND2BX1 add_35_2_g164(.AN (add_35_2_n_19), .B (add_35_2_n_15), .Y
       (add_35_2_n_25));
  NAND2BX1 add_35_2_g166(.AN (add_35_2_n_11), .B (n_52), .Y
       (add_35_2_n_24));
  NAND2X1 add_35_2_g168(.A (add_35_2_n_9), .B (add_35_2_n_18), .Y
       (add_35_2_n_23));
  NOR2X1 add_35_2_g169(.A (add_35_2_n_8), .B (add_35_2_n_16), .Y
       (add_35_2_n_22));
  OR2XL add_35_2_g170(.A (add_35_2_n_6), .B (add_35_2_n_11), .Y
       (add_35_2_n_21));
  NOR2BX1 add_35_2_g172(.AN (add_35_2_n_14), .B (add_35_2_n_6), .Y
       (add_35_2_n_20));
  NOR2X1 add_35_2_g174(.A (in2[5]), .B (in1[1]), .Y (add_35_2_n_19));
  INVX1 add_35_2_g175(.A (add_35_2_n_17), .Y (add_35_2_n_18));
  NOR2X1 add_35_2_g176(.A (in2[4]), .B (in1[1]), .Y (add_35_2_n_17));
  NOR2X2 add_35_2_g177(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_16));
  NAND2X1 add_35_2_g178(.A (in2[5]), .B (in1[1]), .Y (add_35_2_n_15));
  NAND2X1 add_35_2_g179(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_14));
  OR2X1 add_35_2_g180(.A (in2[6]), .B (in1[1]), .Y (add_35_2_n_13));
  NAND2X6 add_35_2_g181(.A (in2[2]), .B (in1[1]), .Y (n_53));
  NOR2X2 add_35_2_g182(.A (in2[2]), .B (in1[1]), .Y (add_35_2_n_11));
  INVX1 add_35_2_g183(.A (add_35_2_n_9), .Y (add_35_2_n_10));
  NAND2X1 add_35_2_g184(.A (in2[4]), .B (in1[1]), .Y (add_35_2_n_9));
  CLKAND2X2 add_35_2_g185(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_8));
  NAND2X1 add_35_2_g186(.A (in2[6]), .B (in1[1]), .Y (add_35_2_n_7));
  NOR2X6 add_35_2_g187(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_6));
  NAND2X8 add_35_2_g188(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_5));
  XNOR2X1 add_35_2_g2(.A (add_35_2_n_5), .B (add_35_2_n_22), .Y
       (out1[1]));
  CLKXOR2X1 add_35_2_g190(.A (add_35_2_n_24), .B (add_35_2_n_34), .Y
       (out1[2]));
  XNOR2XL add_35_2_g191(.A (add_35_2_n_23), .B (add_35_2_n_36), .Y
       (out1[4]));
  CLKXOR2X1 add_35_2_g192(.A (add_35_2_n_20), .B (add_35_2_n_37), .Y
       (out1[3]));
  CLKXOR2X1 add_35_2_g193(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  BUFX3 fopt(.A (n_53), .Y (n_52));
endmodule


