`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_N_Muxb_1_2_13_1(in3, in2, ctrl1, out1);
  input in3, in2, ctrl1;
  output out1;
  wire in3, in2, ctrl1;
  wire out1;
  wire n_0, n_1;
  OAI21X1 g11(.A0 (ctrl1), .A1 (n_0), .B0 (n_1), .Y (out1));
  NAND2X6 g12(.A (in2), .B (ctrl1), .Y (n_1));
  INVX1 g13(.A (in3), .Y (n_0));
endmodule


