`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Mul_8Ux3U_8U_1(in2, in1, out1);
  input [7:0] in2;
  input [2:0] in1;
  output [7:0] out1;
  wire [7:0] in2;
  wire [2:0] in1;
  wire [7:0] out1;
  wire mul_34_8_n_2, mul_34_8_n_3, mul_34_8_n_4, mul_34_8_n_5,
       mul_34_8_n_11, mul_34_8_n_14, mul_34_8_n_15, mul_34_8_n_16;
  wire mul_34_8_n_17, mul_34_8_n_18, mul_34_8_n_19, mul_34_8_n_20,
       mul_34_8_n_22, mul_34_8_n_24, mul_34_8_n_25, mul_34_8_n_26;
  wire mul_34_8_n_27, mul_34_8_n_28, mul_34_8_n_29, mul_34_8_n_32,
       mul_34_8_n_33, mul_34_8_n_35, mul_34_8_n_36, mul_34_8_n_37;
  wire mul_34_8_n_38, mul_34_8_n_39, mul_34_8_n_40, mul_34_8_n_42,
       mul_34_8_n_43, mul_34_8_n_44, mul_34_8_n_45, mul_34_8_n_46;
  wire mul_34_8_n_47, mul_34_8_n_48, mul_34_8_n_49, mul_34_8_n_50,
       mul_34_8_n_51, mul_34_8_n_52, mul_34_8_n_53, mul_34_8_n_54;
  wire mul_34_8_n_55, mul_34_8_n_56, mul_34_8_n_57, mul_34_8_n_58,
       mul_34_8_n_59, mul_34_8_n_60, mul_34_8_n_61, mul_34_8_n_62;
  wire mul_34_8_n_63, mul_34_8_n_64, mul_34_8_n_65, mul_34_8_n_66,
       mul_34_8_n_67, mul_34_8_n_68, mul_34_8_n_69, mul_34_8_n_71;
  wire mul_34_8_n_72, mul_34_8_n_73, mul_34_8_n_74, mul_34_8_n_75,
       mul_34_8_n_76, mul_34_8_n_77, mul_34_8_n_78, mul_34_8_n_79;
  wire mul_34_8_n_80, mul_34_8_n_81, mul_34_8_n_82, mul_34_8_n_83,
       mul_34_8_n_84, mul_34_8_n_85, mul_34_8_n_86, mul_34_8_n_87;
  wire mul_34_8_n_88, mul_34_8_n_89, mul_34_8_n_90, n_103, n_104,
       n_105, n_106, n_107;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_136, n_139, n_167;
  wire n_168;
  MXI2XL mul_34_8_g614(.A (mul_34_8_n_80), .B (mul_34_8_n_79), .S0
       (mul_34_8_n_90), .Y (out1[7]));
  OAI21X1 mul_34_8_g615(.A0 (mul_34_8_n_87), .A1 (mul_34_8_n_86), .B0
       (mul_34_8_n_85), .Y (mul_34_8_n_90));
  OAI21X1 mul_34_8_g616(.A0 (mul_34_8_n_87), .A1 (mul_34_8_n_84), .B0
       (mul_34_8_n_75), .Y (mul_34_8_n_89));
  NOR2X1 mul_34_8_g618(.A (mul_34_8_n_66), .B (mul_34_8_n_87), .Y
       (mul_34_8_n_88));
  NOR2X2 mul_34_8_g621(.A (mul_34_8_n_63), .B (mul_34_8_n_5), .Y
       (mul_34_8_n_87));
  NAND2X1 mul_34_8_g624(.A (mul_34_8_n_77), .B (mul_34_8_n_83), .Y
       (mul_34_8_n_86));
  AOI21X1 mul_34_8_g625(.A0 (mul_34_8_n_76), .A1 (mul_34_8_n_77), .B0
       (mul_34_8_n_74), .Y (mul_34_8_n_85));
  INVX1 mul_34_8_g626(.A (mul_34_8_n_83), .Y (mul_34_8_n_84));
  NOR2X2 mul_34_8_g627(.A (mul_34_8_n_66), .B (mul_34_8_n_73), .Y
       (mul_34_8_n_83));
  NOR2BX1 mul_34_8_g629(.AN (mul_34_8_n_75), .B (mul_34_8_n_73), .Y
       (mul_34_8_n_82));
  NOR2BX1 mul_34_8_g631(.AN (mul_34_8_n_77), .B (mul_34_8_n_74), .Y
       (mul_34_8_n_81));
  INVX1 mul_34_8_g632(.A (mul_34_8_n_79), .Y (mul_34_8_n_80));
  XNOR2X1 mul_34_8_g633(.A (mul_34_8_n_62), .B (mul_34_8_n_69), .Y
       (mul_34_8_n_79));
  AOI21X2 mul_34_8_g634(.A0 (mul_34_8_n_59), .A1 (mul_34_8_n_57), .B0
       (mul_34_8_n_58), .Y (mul_34_8_n_78));
  NAND2X2 mul_34_8_g636(.A (mul_34_8_n_60), .B (mul_34_8_n_67), .Y
       (mul_34_8_n_77));
  INVX1 mul_34_8_g637(.A (mul_34_8_n_75), .Y (mul_34_8_n_76));
  NAND2X1 mul_34_8_g638(.A (mul_34_8_n_65), .B (mul_34_8_n_68), .Y
       (mul_34_8_n_75));
  NOR2X1 mul_34_8_g639(.A (mul_34_8_n_60), .B (mul_34_8_n_67), .Y
       (mul_34_8_n_74));
  NOR2X1 mul_34_8_g640(.A (mul_34_8_n_65), .B (mul_34_8_n_68), .Y
       (mul_34_8_n_73));
  NOR2BX1 mul_34_8_g644(.AN (mul_34_8_n_61), .B (mul_34_8_n_63), .Y
       (mul_34_8_n_72));
  NOR2BX1 mul_34_8_g645(.AN (mul_34_8_n_57), .B (mul_34_8_n_58), .Y
       (mul_34_8_n_71));
  NOR2BX1 mul_34_8_g646(.AN (mul_34_8_n_64), .B (mul_34_8_n_59), .Y
       (out1[1]));
  XNOR2X1 mul_34_8_g647(.A (mul_34_8_n_49), .B (mul_34_8_n_55), .Y
       (mul_34_8_n_69));
  XNOR2X1 mul_34_8_g648(.A (mul_34_8_n_46), .B (mul_34_8_n_52), .Y
       (mul_34_8_n_68));
  CLKXOR2X1 mul_34_8_g649(.A (mul_34_8_n_51), .B (mul_34_8_n_53), .Y
       (mul_34_8_n_67));
  XNOR2X1 mul_34_8_g650(.A (mul_34_8_n_50), .B (mul_34_8_n_56), .Y
       (mul_34_8_n_66));
  NOR2X1 mul_34_8_g651(.A (mul_34_8_n_56), .B (mul_34_8_n_50), .Y
       (mul_34_8_n_65));
  NAND2X1 mul_34_8_g652(.A (mul_34_8_n_36), .B (mul_34_8_n_45), .Y
       (mul_34_8_n_64));
  NOR2X1 mul_34_8_g653(.A (mul_34_8_n_54), .B (mul_34_8_n_48), .Y
       (mul_34_8_n_63));
  NOR2BX1 mul_34_8_g654(.AN (mul_34_8_n_51), .B (mul_34_8_n_53), .Y
       (mul_34_8_n_62));
  NAND2X1 mul_34_8_g656(.A (mul_34_8_n_54), .B (mul_34_8_n_48), .Y
       (mul_34_8_n_61));
  NAND2BX1 mul_34_8_g657(.AN (mul_34_8_n_52), .B (mul_34_8_n_46), .Y
       (mul_34_8_n_60));
  NOR2X2 mul_34_8_g658(.A (mul_34_8_n_36), .B (mul_34_8_n_45), .Y
       (mul_34_8_n_59));
  NOR2X1 mul_34_8_g659(.A (mul_34_8_n_42), .B (mul_34_8_n_47), .Y
       (mul_34_8_n_58));
  NAND2X1 mul_34_8_g660(.A (mul_34_8_n_42), .B (mul_34_8_n_47), .Y
       (mul_34_8_n_57));
  AOI22X1 mul_34_8_g661(.A0 (in2[1]), .A1 (mul_34_8_n_43), .B0
       (in2[2]), .B1 (n_136), .Y (mul_34_8_n_56));
  AOI22X1 mul_34_8_g662(.A0 (in2[4]), .A1 (mul_34_8_n_43), .B0
       (in2[5]), .B1 (n_136), .Y (mul_34_8_n_55));
  NOR2X1 mul_34_8_g663(.A (mul_34_8_n_3), .B (mul_34_8_n_44), .Y
       (mul_34_8_n_54));
  AOI22X1 mul_34_8_g664(.A0 (in2[3]), .A1 (mul_34_8_n_43), .B0
       (in2[4]), .B1 (n_136), .Y (mul_34_8_n_53));
  AOI22X2 mul_34_8_g665(.A0 (in2[2]), .A1 (mul_34_8_n_43), .B0
       (in2[3]), .B1 (n_136), .Y (mul_34_8_n_52));
  OAI2BB1X1 mul_34_8_g666(.A0N (mul_34_8_n_28), .A1N (n_167), .B0
       (mul_34_8_n_39), .Y (mul_34_8_n_51));
  AOI21X1 mul_34_8_g667(.A0 (mul_34_8_n_26), .A1 (n_167), .B0
       (mul_34_8_n_4), .Y (mul_34_8_n_50));
  AOI22X1 mul_34_8_g668(.A0 (n_103), .A1 (n_168), .B0 (n_116), .B1
       (mul_34_8_n_29), .Y (mul_34_8_n_49));
  AOI21X1 mul_34_8_g669(.A0 (n_104), .A1 (n_168), .B0 (mul_34_8_n_38),
       .Y (mul_34_8_n_48));
  AOI21X1 mul_34_8_g670(.A0 (mul_34_8_n_33), .A1 (n_167), .B0
       (mul_34_8_n_2), .Y (mul_34_8_n_47));
  OAI2BB1X1 mul_34_8_g671(.A0N (mul_34_8_n_35), .A1N (n_167), .B0
       (mul_34_8_n_40), .Y (mul_34_8_n_46));
  AOI21X2 mul_34_8_g672(.A0 (mul_34_8_n_27), .A1 (n_167), .B0
       (mul_34_8_n_37), .Y (mul_34_8_n_45));
  AND2X1 mul_34_8_g673(.A (in2[0]), .B (mul_34_8_n_43), .Y
       (mul_34_8_n_44));
  NOR2X4 mul_34_8_g674(.A (mul_34_8_n_14), .B (n_139), .Y
       (mul_34_8_n_43));
  NAND2X1 mul_34_8_g675(.A (in2[0]), .B (n_136), .Y (mul_34_8_n_42));
  NOR2X6 mul_34_8_g677(.A (n_121), .B (mul_34_8_n_24), .Y (n_167));
  NAND2X1 mul_34_8_g678(.A (n_121), .B (mul_34_8_n_28), .Y
       (mul_34_8_n_40));
  NAND2X1 mul_34_8_g679(.A (n_118), .B (n_103), .Y (mul_34_8_n_39));
  NOR2X1 mul_34_8_g681(.A (n_117), .B (mul_34_8_n_25), .Y
       (mul_34_8_n_38));
  NOR2X1 mul_34_8_g682(.A (n_119), .B (mul_34_8_n_32), .Y
       (mul_34_8_n_37));
  NAND2X1 mul_34_8_g684(.A (n_113), .B (mul_34_8_n_20), .Y
       (mul_34_8_n_36));
  MXI2XL mul_34_8_g686(.A (n_114), .B (n_106), .S0 (in2[4]), .Y
       (mul_34_8_n_35));
  NAND2X8 mul_34_8_g688(.A (mul_34_8_n_22), .B (mul_34_8_n_19), .Y
       (n_139));
  INVX1 mul_34_8_g689(.A (mul_34_8_n_32), .Y (mul_34_8_n_33));
  NOR2X1 mul_34_8_g690(.A (mul_34_8_n_17), .B (mul_34_8_n_18), .Y
       (mul_34_8_n_32));
  MXI2XL mul_34_8_g694(.A (n_112), .B (n_113), .S0 (in2[7]), .Y
       (mul_34_8_n_29));
  MXI2X1 mul_34_8_g695(.A (n_107), .B (n_109), .S0 (in2[5]), .Y
       (mul_34_8_n_28));
  MXI2X1 mul_34_8_g696(.A (n_105), .B (n_109), .S0 (in2[0]), .Y
       (mul_34_8_n_27));
  INVX1 mul_34_8_g697(.A (mul_34_8_n_25), .Y (mul_34_8_n_26));
  MXI2XL mul_34_8_g698(.A (n_106), .B (n_114), .S0 (in2[3]), .Y
       (mul_34_8_n_25));
  NOR2X4 mul_34_8_g699(.A (mul_34_8_n_15), .B (mul_34_8_n_16), .Y
       (mul_34_8_n_24));
  NAND2X6 mul_34_8_g702(.A (in1[1]), .B (mul_34_8_n_14), .Y
       (mul_34_8_n_22));
  INVX1 mul_34_8_g703(.A (mul_34_8_n_20), .Y (out1[0]));
  NAND2X1 mul_34_8_g704(.A (in2[0]), .B (n_121), .Y (mul_34_8_n_20));
  NAND2X4 mul_34_8_g705(.A (in1[2]), .B (n_110), .Y (mul_34_8_n_19));
  NOR2X1 mul_34_8_g707(.A (mul_34_8_n_11), .B (n_106), .Y
       (mul_34_8_n_18));
  NOR2X1 mul_34_8_g708(.A (n_105), .B (in2[1]), .Y (mul_34_8_n_17));
  NOR2X4 mul_34_8_g709(.A (in1[1]), .B (n_122), .Y (mul_34_8_n_16));
  NOR2X4 mul_34_8_g710(.A (in1[0]), .B (n_111), .Y (mul_34_8_n_15));
  CLKINVX6 mul_34_8_g712(.A (in1[2]), .Y (mul_34_8_n_14));
  INVX1 mul_34_8_g716(.A (in2[1]), .Y (mul_34_8_n_11));
  XNOR2X1 mul_34_8_g2(.A (mul_34_8_n_72), .B (mul_34_8_n_78), .Y
       (out1[3]));
  CLKXOR2X1 mul_34_8_g717(.A (mul_34_8_n_66), .B (mul_34_8_n_87), .Y
       (out1[4]));
  CLKXOR2X1 mul_34_8_g718(.A (mul_34_8_n_82), .B (mul_34_8_n_88), .Y
       (out1[5]));
  XOR2XL mul_34_8_g719(.A (mul_34_8_n_81), .B (mul_34_8_n_89), .Y
       (out1[6]));
  CLKXOR2X1 mul_34_8_g720(.A (mul_34_8_n_59), .B (mul_34_8_n_71), .Y
       (out1[2]));
  NOR2BX1 mul_34_8_g721(.AN (mul_34_8_n_61), .B (mul_34_8_n_78), .Y
       (mul_34_8_n_5));
  NOR2BX1 mul_34_8_g722(.AN (mul_34_8_n_35), .B (n_117), .Y
       (mul_34_8_n_4));
  NOR2BX1 mul_34_8_g723(.AN (n_136), .B (mul_34_8_n_11), .Y
       (mul_34_8_n_3));
  NOR2BX1 mul_34_8_g724(.AN (n_104), .B (n_120), .Y (mul_34_8_n_2));
  MX2XL g2(.A (n_109), .B (n_105), .S0 (in2[6]), .Y (n_103));
  MX2XL g727(.A (in1[1]), .B (n_110), .S0 (in2[2]), .Y (n_104));
  CLKINVX1 fopt(.A (in1[1]), .Y (n_105));
  CLKINVX2 fopt728(.A (n_107), .Y (n_106));
  CLKINVX4 fopt729(.A (in1[1]), .Y (n_107));
  CLKINVX2 fopt730(.A (n_110), .Y (n_109));
  CLKINVX8 fopt731(.A (in1[1]), .Y (n_110));
  CLKINVX8 fopt732(.A (in1[1]), .Y (n_111));
  CLKINVX1 fopt733(.A (n_113), .Y (n_112));
  CLKINVX1 fopt734(.A (n_114), .Y (n_113));
  CLKINVX1 fopt735(.A (in1[1]), .Y (n_114));
  CLKINVX1 fopt736(.A (n_117), .Y (n_116));
  CLKINVX1 fopt737(.A (n_118), .Y (n_117));
  CLKINVX1 fopt738(.A (n_119), .Y (n_118));
  CLKINVX3 fopt739(.A (n_121), .Y (n_119));
  CLKINVX1 fopt740(.A (n_121), .Y (n_120));
  BUFX3 fopt741(.A (in1[0]), .Y (n_121));
  CLKINVX3 fopt742(.A (in1[0]), .Y (n_122));
  BUFX3 fopt752(.A (n_139), .Y (n_136));
  BUFX3 fopt773(.A (n_167), .Y (n_168));
endmodule


