`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Mul2i7u8_1(in1, out1);
  input [7:0] in1;
  output [7:0] out1;
  wire [7:0] in1;
  wire [7:0] out1;
  wire const_mul_32_8_n_0, const_mul_32_8_n_1, const_mul_32_8_n_2,
       const_mul_32_8_n_5, const_mul_32_8_n_6, const_mul_32_8_n_8,
       const_mul_32_8_n_9, const_mul_32_8_n_10;
  wire const_mul_32_8_n_11, const_mul_32_8_n_12, const_mul_32_8_n_13,
       const_mul_32_8_n_14, const_mul_32_8_n_16, const_mul_32_8_n_17,
       const_mul_32_8_n_18, const_mul_32_8_n_20;
  wire const_mul_32_8_n_21, const_mul_32_8_n_22, const_mul_32_8_n_23,
       const_mul_32_8_n_24, const_mul_32_8_n_25, const_mul_32_8_n_26,
       const_mul_32_8_n_27, const_mul_32_8_n_28;
  wire const_mul_32_8_n_29, const_mul_32_8_n_30, const_mul_32_8_n_32,
       const_mul_32_8_n_33, const_mul_32_8_n_34, const_mul_32_8_n_35,
       const_mul_32_8_n_38, const_mul_32_8_n_39;
  wire n_50, n_51, n_73, n_74, n_75, n_76, n_77, n_78;
  assign out1[0] = in1[0];
  MXI2XL const_mul_32_8_g246(.A (const_mul_32_8_n_25), .B
       (const_mul_32_8_n_24), .S0 (const_mul_32_8_n_39), .Y (out1[6]));
  MXI2XL const_mul_32_8_g248(.A (const_mul_32_8_n_20), .B
       (const_mul_32_8_n_21), .S0 (const_mul_32_8_n_35), .Y (out1[7]));
  OAI21X1 const_mul_32_8_g249(.A0 (const_mul_32_8_n_26), .A1
       (const_mul_32_8_n_2), .B0 (const_mul_32_8_n_28), .Y
       (const_mul_32_8_n_39));
  OAI21X2 const_mul_32_8_g250(.A0 (const_mul_32_8_n_12), .A1
       (const_mul_32_8_n_2), .B0 (const_mul_32_8_n_10), .Y
       (const_mul_32_8_n_38));
  MXI2XL const_mul_32_8_g251(.A (const_mul_32_8_n_22), .B
       (const_mul_32_8_n_23), .S0 (const_mul_32_8_n_2), .Y (out1[4]));
  OAI2BB2XL const_mul_32_8_g252(.A0N (const_mul_32_8_n_30), .A1N
       (const_mul_32_8_n_0), .B0 (const_mul_32_8_n_30), .B1
       (const_mul_32_8_n_0), .Y (out1[3]));
  NOR2X1 const_mul_32_8_g253(.A (const_mul_32_8_n_33), .B
       (const_mul_32_8_n_34), .Y (const_mul_32_8_n_35));
  NOR2X1 const_mul_32_8_g254(.A (const_mul_32_8_n_2), .B
       (const_mul_32_8_n_29), .Y (const_mul_32_8_n_34));
  OAI21X1 const_mul_32_8_g256(.A0 (const_mul_32_8_n_16), .A1
       (const_mul_32_8_n_28), .B0 (const_mul_32_8_n_17), .Y
       (const_mul_32_8_n_33));
  NOR3X2 const_mul_32_8_g257(.A (n_74), .B (const_mul_32_8_n_11), .C
       (n_51), .Y (const_mul_32_8_n_32));
  MXI2XL const_mul_32_8_g258(.A (n_76), .B (n_75), .S0 (n_50), .Y
       (out1[2]));
  NOR2X1 const_mul_32_8_g259(.A (n_77), .B (n_50), .Y
       (const_mul_32_8_n_30));
  NAND2BX1 const_mul_32_8_g260(.AN (const_mul_32_8_n_16), .B
       (const_mul_32_8_n_1), .Y (const_mul_32_8_n_29));
  AOI21X2 const_mul_32_8_g261(.A0 (const_mul_32_8_n_13), .A1
       (const_mul_32_8_n_9), .B0 (const_mul_32_8_n_14), .Y
       (const_mul_32_8_n_28));
  NAND2BX1 const_mul_32_8_g263(.AN (const_mul_32_8_n_14), .B
       (const_mul_32_8_n_13), .Y (const_mul_32_8_n_27));
  INVX1 const_mul_32_8_g264(.A (const_mul_32_8_n_1), .Y
       (const_mul_32_8_n_26));
  INVX1 const_mul_32_8_g267(.A (const_mul_32_8_n_24), .Y
       (const_mul_32_8_n_25));
  NOR2BX1 const_mul_32_8_g268(.AN (const_mul_32_8_n_17), .B
       (const_mul_32_8_n_16), .Y (const_mul_32_8_n_24));
  INVX1 const_mul_32_8_g269(.A (const_mul_32_8_n_22), .Y
       (const_mul_32_8_n_23));
  NOR2X1 const_mul_32_8_g270(.A (const_mul_32_8_n_9), .B
       (const_mul_32_8_n_12), .Y (const_mul_32_8_n_22));
  INVX1 const_mul_32_8_g271(.A (const_mul_32_8_n_20), .Y
       (const_mul_32_8_n_21));
  XNOR2X1 const_mul_32_8_g272(.A (in1[7]), .B (in1[4]), .Y
       (const_mul_32_8_n_20));
  MXI2XL const_mul_32_8_g273(.A (const_mul_32_8_n_8), .B (in1[1]), .S0
       (in1[0]), .Y (out1[1]));
  NAND2X1 const_mul_32_8_g275(.A (in1[0]), .B (const_mul_32_8_n_6), .Y
       (const_mul_32_8_n_18));
  NAND2BX1 const_mul_32_8_g276(.AN (in1[6]), .B (in1[3]), .Y
       (const_mul_32_8_n_17));
  NOR2BX1 const_mul_32_8_g277(.AN (in1[6]), .B (in1[3]), .Y
       (const_mul_32_8_n_16));
  NAND2X4 const_mul_32_8_g278(.A (const_mul_32_8_n_8), .B
       (const_mul_32_8_n_5), .Y (n_51));
  NOR2X1 const_mul_32_8_g279(.A (n_78), .B (in1[5]), .Y
       (const_mul_32_8_n_14));
  NAND2X4 const_mul_32_8_g281(.A (in1[5]), .B (n_73), .Y
       (const_mul_32_8_n_13));
  NOR2BX1 const_mul_32_8_g282(.AN (in1[4]), .B (in1[1]), .Y
       (const_mul_32_8_n_12));
  NOR2X2 const_mul_32_8_g284(.A (in1[0]), .B (const_mul_32_8_n_6), .Y
       (const_mul_32_8_n_11));
  INVX1 const_mul_32_8_g285(.A (const_mul_32_8_n_9), .Y
       (const_mul_32_8_n_10));
  NOR2X2 const_mul_32_8_g286(.A (in1[4]), .B (const_mul_32_8_n_8), .Y
       (const_mul_32_8_n_9));
  CLKINVX8 const_mul_32_8_g287(.A (in1[1]), .Y (const_mul_32_8_n_8));
  CLKINVX12 const_mul_32_8_g289(.A (in1[3]), .Y (const_mul_32_8_n_6));
  CLKINVX3 const_mul_32_8_g290(.A (in1[0]), .Y (const_mul_32_8_n_5));
  XNOR2XL const_mul_32_8_g2(.A (const_mul_32_8_n_27), .B
       (const_mul_32_8_n_38), .Y (out1[5]));
  NOR2BX2 const_mul_32_8_g291(.AN (const_mul_32_8_n_18), .B
       (const_mul_32_8_n_32), .Y (const_mul_32_8_n_2));
  NOR2BX1 const_mul_32_8_g292(.AN (const_mul_32_8_n_13), .B
       (const_mul_32_8_n_12), .Y (const_mul_32_8_n_1));
  NAND2BX1 const_mul_32_8_g293(.AN (const_mul_32_8_n_11), .B
       (const_mul_32_8_n_18), .Y (const_mul_32_8_n_0));
  BUFX3 fopt(.A (n_51), .Y (n_50));
  CLKINVX6 fopt312(.A (in1[2]), .Y (n_73));
  CLKINVX2 fopt313(.A (n_78), .Y (n_74));
  CLKINVX1 fopt314(.A (n_76), .Y (n_75));
  CLKINVX1 fopt315(.A (n_77), .Y (n_76));
  CLKINVX1 fopt316(.A (n_78), .Y (n_77));
  CLKINVX3 fopt317(.A (in1[2]), .Y (n_78));
endmodule


