`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_LtiLLs12_4(in1, out1);
  input [11:0] in1;
  output out1;
  wire [11:0] in1;
  wire out1;
  NAND2BXL gt_31_65_g204(.AN (in1[11]), .B (in1[10]), .Y (out1));
endmodule


