`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Mul_10Ux3U_10U_4(in2, in1, out1);
  input [9:0] in2;
  input [2:0] in1;
  output [9:0] out1;
  wire [9:0] in2;
  wire [2:0] in1;
  wire [9:0] out1;
  wire mul_34_8_n_0, mul_34_8_n_1, mul_34_8_n_3, mul_34_8_n_4,
       mul_34_8_n_5, mul_34_8_n_6, mul_34_8_n_7, mul_34_8_n_8;
  wire mul_34_8_n_9, mul_34_8_n_10, mul_34_8_n_11, mul_34_8_n_12,
       mul_34_8_n_13, mul_34_8_n_14, mul_34_8_n_15, mul_34_8_n_16;
  wire mul_34_8_n_17, mul_34_8_n_18, mul_34_8_n_19, mul_34_8_n_20,
       mul_34_8_n_21, mul_34_8_n_22, mul_34_8_n_23, mul_34_8_n_24;
  wire mul_34_8_n_25, mul_34_8_n_26, mul_34_8_n_27, mul_34_8_n_28,
       mul_34_8_n_29, mul_34_8_n_30, mul_34_8_n_31, mul_34_8_n_32;
  wire mul_34_8_n_33, mul_34_8_n_34, mul_34_8_n_35, mul_34_8_n_36,
       mul_34_8_n_37, mul_34_8_n_38, mul_34_8_n_39, mul_34_8_n_40;
  wire mul_34_8_n_41, mul_34_8_n_42, mul_34_8_n_43, mul_34_8_n_44,
       mul_34_8_n_46, mul_34_8_n_47, mul_34_8_n_48, mul_34_8_n_49;
  wire mul_34_8_n_50, mul_34_8_n_51, mul_34_8_n_52, mul_34_8_n_53,
       mul_34_8_n_54, mul_34_8_n_55, mul_34_8_n_56, mul_34_8_n_57;
  wire mul_34_8_n_58, mul_34_8_n_59, mul_34_8_n_60, mul_34_8_n_61,
       mul_34_8_n_62, mul_34_8_n_63, mul_34_8_n_64, mul_34_8_n_65;
  wire mul_34_8_n_67, mul_34_8_n_68, mul_34_8_n_69, mul_34_8_n_70,
       mul_34_8_n_73, mul_34_8_n_74, mul_34_8_n_76, mul_34_8_n_78;
  wire mul_34_8_n_79, mul_34_8_n_81, mul_34_8_n_82;
  XNOR2X1 mul_34_8_g781(.A (mul_34_8_n_58), .B (mul_34_8_n_81), .Y
       (out1[9]));
  INVX1 mul_34_8_g782(.A (mul_34_8_n_82), .Y (out1[8]));
  ADDFX1 mul_34_8_g783(.A (mul_34_8_n_78), .B (mul_34_8_n_38), .CI
       (mul_34_8_n_42), .CO (mul_34_8_n_81), .S (mul_34_8_n_82));
  XNOR2X1 mul_34_8_g784(.A (mul_34_8_n_61), .B (mul_34_8_n_79), .Y
       (out1[7]));
  OAI2BB1X1 mul_34_8_g785(.A0N (mul_34_8_n_54), .A1N (mul_34_8_n_76),
       .B0 (mul_34_8_n_56), .Y (mul_34_8_n_79));
  AOI211XL mul_34_8_g786(.A0 (mul_34_8_n_63), .A1 (mul_34_8_n_74), .B0
       (mul_34_8_n_67), .C0 (mul_34_8_n_53), .Y (mul_34_8_n_78));
  XNOR2X1 mul_34_8_g787(.A (mul_34_8_n_60), .B (mul_34_8_n_76), .Y
       (out1[6]));
  NAND2BX1 mul_34_8_g788(.AN (mul_34_8_n_74), .B (mul_34_8_n_55), .Y
       (mul_34_8_n_76));
  XNOR2X1 mul_34_8_g789(.A (mul_34_8_n_59), .B (mul_34_8_n_73), .Y
       (out1[5]));
  NOR2BX1 mul_34_8_g790(.AN (mul_34_8_n_73), .B (mul_34_8_n_52), .Y
       (mul_34_8_n_74));
  ADDHX1 mul_34_8_g791(.A (mul_34_8_n_46), .B (mul_34_8_n_70), .CO
       (mul_34_8_n_73), .S (out1[4]));
  INVX1 mul_34_8_g792(.A (mul_34_8_n_69), .Y (out1[3]));
  INVX1 mul_34_8_g793(.A (mul_34_8_n_68), .Y (mul_34_8_n_70));
  ADDFX1 mul_34_8_g794(.A (mul_34_8_n_64), .B (mul_34_8_n_29), .CI
       (mul_34_8_n_37), .CO (mul_34_8_n_68), .S (mul_34_8_n_69));
  OAI22X1 mul_34_8_g795(.A0 (mul_34_8_n_55), .A1 (mul_34_8_n_62), .B0
       (mul_34_8_n_57), .B1 (mul_34_8_n_56), .Y (mul_34_8_n_67));
  INVX1 mul_34_8_g796(.A (mul_34_8_n_65), .Y (out1[2]));
  ADDFX1 mul_34_8_g797(.A (mul_34_8_n_40), .B (mul_34_8_n_28), .CI
       (mul_34_8_n_20), .CO (mul_34_8_n_64), .S (mul_34_8_n_65));
  INVX1 mul_34_8_g798(.A (mul_34_8_n_62), .Y (mul_34_8_n_63));
  NAND2BX1 mul_34_8_g799(.AN (mul_34_8_n_57), .B (mul_34_8_n_54), .Y
       (mul_34_8_n_62));
  OR2XL mul_34_8_g800(.A (mul_34_8_n_53), .B (mul_34_8_n_57), .Y
       (mul_34_8_n_61));
  NAND2X1 mul_34_8_g801(.A (mul_34_8_n_56), .B (mul_34_8_n_54), .Y
       (mul_34_8_n_60));
  NAND2BX1 mul_34_8_g802(.AN (mul_34_8_n_52), .B (mul_34_8_n_55), .Y
       (mul_34_8_n_59));
  XNOR2X1 mul_34_8_g803(.A (mul_34_8_n_39), .B (mul_34_8_n_44), .Y
       (mul_34_8_n_58));
  NOR2X1 mul_34_8_g804(.A (mul_34_8_n_48), .B (mul_34_8_n_43), .Y
       (mul_34_8_n_57));
  NAND2X1 mul_34_8_g805(.A (mul_34_8_n_50), .B (mul_34_8_n_49), .Y
       (mul_34_8_n_56));
  NAND2X1 mul_34_8_g806(.A (mul_34_8_n_47), .B (mul_34_8_n_51), .Y
       (mul_34_8_n_55));
  OR2X1 mul_34_8_g807(.A (mul_34_8_n_50), .B (mul_34_8_n_49), .Y
       (mul_34_8_n_54));
  AND2XL mul_34_8_g808(.A (mul_34_8_n_48), .B (mul_34_8_n_43), .Y
       (mul_34_8_n_53));
  NOR2X1 mul_34_8_g809(.A (mul_34_8_n_47), .B (mul_34_8_n_51), .Y
       (mul_34_8_n_52));
  ADDHX1 mul_34_8_g810(.A (mul_34_8_n_35), .B (mul_34_8_n_24), .CO
       (mul_34_8_n_50), .S (mul_34_8_n_51));
  ADDHX1 mul_34_8_g811(.A (mul_34_8_n_31), .B (mul_34_8_n_26), .CO
       (mul_34_8_n_48), .S (mul_34_8_n_49));
  ADDHX1 mul_34_8_g812(.A (mul_34_8_n_32), .B (mul_34_8_n_23), .CO
       (mul_34_8_n_47), .S (mul_34_8_n_46));
  AOI21X1 mul_34_8_g813(.A0 (mul_34_8_n_17), .A1 (mul_34_8_n_25), .B0
       (mul_34_8_n_41), .Y (out1[1]));
  XNOR2X1 mul_34_8_g814(.A (mul_34_8_n_27), .B (mul_34_8_n_36), .Y
       (mul_34_8_n_44));
  XNOR2X1 mul_34_8_g815(.A (mul_34_8_n_22), .B (mul_34_8_n_33), .Y
       (mul_34_8_n_43));
  XNOR2X1 mul_34_8_g816(.A (mul_34_8_n_30), .B (mul_34_8_n_34), .Y
       (mul_34_8_n_42));
  INVX1 mul_34_8_g817(.A (mul_34_8_n_40), .Y (mul_34_8_n_41));
  OR2X1 mul_34_8_g818(.A (mul_34_8_n_17), .B (mul_34_8_n_25), .Y
       (mul_34_8_n_40));
  NOR2X1 mul_34_8_g819(.A (mul_34_8_n_34), .B (mul_34_8_n_30), .Y
       (mul_34_8_n_39));
  NAND2BX1 mul_34_8_g820(.AN (mul_34_8_n_33), .B (mul_34_8_n_22), .Y
       (mul_34_8_n_38));
  AOI22X1 mul_34_8_g821(.A0 (in2[0]), .A1 (mul_34_8_n_21), .B0
       (in2[1]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_37));
  AOI22X1 mul_34_8_g822(.A0 (in2[6]), .A1 (mul_34_8_n_21), .B0
       (in2[7]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_36));
  AO22XL mul_34_8_g823(.A0 (in2[2]), .A1 (mul_34_8_n_21), .B0 (in2[3]),
       .B1 (mul_34_8_n_11), .Y (mul_34_8_n_35));
  AOI22X1 mul_34_8_g824(.A0 (in2[5]), .A1 (mul_34_8_n_21), .B0
       (in2[6]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_34));
  AOI22X1 mul_34_8_g825(.A0 (in2[4]), .A1 (mul_34_8_n_21), .B0
       (in2[5]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_33));
  AO22XL mul_34_8_g826(.A0 (in2[1]), .A1 (mul_34_8_n_21), .B0 (in2[2]),
       .B1 (mul_34_8_n_11), .Y (mul_34_8_n_32));
  AO22XL mul_34_8_g827(.A0 (in2[3]), .A1 (mul_34_8_n_21), .B0 (in2[4]),
       .B1 (mul_34_8_n_11), .Y (mul_34_8_n_31));
  AOI22X1 mul_34_8_g828(.A0 (mul_34_8_n_6), .A1 (mul_34_8_n_19), .B0
       (in1[0]), .B1 (mul_34_8_n_10), .Y (mul_34_8_n_30));
  AOI22X1 mul_34_8_g829(.A0 (mul_34_8_n_16), .A1 (mul_34_8_n_19), .B0
       (in1[0]), .B1 (mul_34_8_n_7), .Y (mul_34_8_n_29));
  AOI22X1 mul_34_8_g830(.A0 (mul_34_8_n_15), .A1 (mul_34_8_n_19), .B0
       (in1[0]), .B1 (mul_34_8_n_16), .Y (mul_34_8_n_28));
  AOI22X1 mul_34_8_g831(.A0 (mul_34_8_n_10), .A1 (mul_34_8_n_19), .B0
       (in1[0]), .B1 (mul_34_8_n_14), .Y (mul_34_8_n_27));
  OAI22X1 mul_34_8_g832(.A0 (mul_34_8_n_13), .A1 (mul_34_8_n_18), .B0
       (mul_34_8_n_0), .B1 (mul_34_8_n_9), .Y (mul_34_8_n_26));
  AOI22X1 mul_34_8_g833(.A0 (mul_34_8_n_12), .A1 (mul_34_8_n_19), .B0
       (in1[0]), .B1 (mul_34_8_n_15), .Y (mul_34_8_n_25));
  OAI22X1 mul_34_8_g834(.A0 (mul_34_8_n_4), .A1 (mul_34_8_n_18), .B0
       (mul_34_8_n_0), .B1 (mul_34_8_n_13), .Y (mul_34_8_n_24));
  OAI22X1 mul_34_8_g835(.A0 (mul_34_8_n_8), .A1 (mul_34_8_n_18), .B0
       (mul_34_8_n_0), .B1 (mul_34_8_n_4), .Y (mul_34_8_n_23));
  OAI22X1 mul_34_8_g836(.A0 (mul_34_8_n_9), .A1 (mul_34_8_n_18), .B0
       (mul_34_8_n_0), .B1 (mul_34_8_n_5), .Y (mul_34_8_n_22));
  NOR2BX1 mul_34_8_g837(.AN (in1[2]), .B (mul_34_8_n_11), .Y
       (mul_34_8_n_21));
  NAND2X1 mul_34_8_g838(.A (in2[0]), .B (mul_34_8_n_11), .Y
       (mul_34_8_n_20));
  INVX1 mul_34_8_g839(.A (mul_34_8_n_19), .Y (mul_34_8_n_18));
  NOR2X1 mul_34_8_g840(.A (in1[0]), .B (mul_34_8_n_3), .Y
       (mul_34_8_n_19));
  NAND2BX1 mul_34_8_g841(.AN (out1[0]), .B (in1[1]), .Y
       (mul_34_8_n_17));
  MXI2XL mul_34_8_g842(.A (mul_34_8_n_1), .B (in1[1]), .S0 (in2[2]), .Y
       (mul_34_8_n_16));
  MXI2XL mul_34_8_g843(.A (mul_34_8_n_1), .B (in1[1]), .S0 (in2[1]), .Y
       (mul_34_8_n_15));
  MXI2XL mul_34_8_g844(.A (mul_34_8_n_1), .B (in1[1]), .S0 (in2[9]), .Y
       (mul_34_8_n_14));
  MX2XL mul_34_8_g845(.A (mul_34_8_n_1), .B (in1[1]), .S0 (in2[5]), .Y
       (mul_34_8_n_13));
  MXI2XL mul_34_8_g846(.A (mul_34_8_n_1), .B (in1[1]), .S0 (in2[0]), .Y
       (mul_34_8_n_12));
  MX2X1 mul_34_8_g847(.A (in1[1]), .B (mul_34_8_n_1), .S0 (in1[2]), .Y
       (mul_34_8_n_11));
  MX2XL mul_34_8_g848(.A (in1[1]), .B (mul_34_8_n_1), .S0 (in2[8]), .Y
       (mul_34_8_n_10));
  MX2XL mul_34_8_g849(.A (mul_34_8_n_1), .B (in1[1]), .S0 (in2[6]), .Y
       (mul_34_8_n_9));
  INVX1 mul_34_8_g850(.A (mul_34_8_n_7), .Y (mul_34_8_n_8));
  MX2XL mul_34_8_g851(.A (in1[1]), .B (mul_34_8_n_1), .S0 (in2[3]), .Y
       (mul_34_8_n_7));
  INVX1 mul_34_8_g852(.A (mul_34_8_n_5), .Y (mul_34_8_n_6));
  MX2X1 mul_34_8_g853(.A (mul_34_8_n_1), .B (in1[1]), .S0 (in2[7]), .Y
       (mul_34_8_n_5));
  MXI2XL mul_34_8_g854(.A (in1[1]), .B (mul_34_8_n_1), .S0 (in2[4]), .Y
       (mul_34_8_n_4));
  AOI22X1 mul_34_8_g855(.A0 (in1[1]), .A1 (mul_34_8_n_0), .B0 (in1[0]),
       .B1 (mul_34_8_n_1), .Y (mul_34_8_n_3));
  AND2XL mul_34_8_g856(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVX1 mul_34_8_g857(.A (in1[1]), .Y (mul_34_8_n_1));
  INVX1 mul_34_8_g858(.A (in1[0]), .Y (mul_34_8_n_0));
endmodule


