`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Mul2i7u10_1(in1, out1);
  input [9:0] in1;
  output [9:0] out1;
  wire [9:0] in1;
  wire [9:0] out1;
  wire const_mul_32_8_n_1, const_mul_32_8_n_2, const_mul_32_8_n_8,
       const_mul_32_8_n_10, const_mul_32_8_n_11, const_mul_32_8_n_12,
       const_mul_32_8_n_13, const_mul_32_8_n_14;
  wire const_mul_32_8_n_15, const_mul_32_8_n_16, const_mul_32_8_n_17,
       const_mul_32_8_n_18, const_mul_32_8_n_19, const_mul_32_8_n_20,
       const_mul_32_8_n_21, const_mul_32_8_n_22;
  wire const_mul_32_8_n_23, const_mul_32_8_n_24, const_mul_32_8_n_25,
       const_mul_32_8_n_26, const_mul_32_8_n_27, const_mul_32_8_n_28,
       const_mul_32_8_n_29, const_mul_32_8_n_30;
  wire const_mul_32_8_n_31, const_mul_32_8_n_32, const_mul_32_8_n_33,
       const_mul_32_8_n_34, const_mul_32_8_n_35, const_mul_32_8_n_36,
       const_mul_32_8_n_37, const_mul_32_8_n_38;
  wire const_mul_32_8_n_39, const_mul_32_8_n_41, const_mul_32_8_n_42,
       const_mul_32_8_n_44, const_mul_32_8_n_45, const_mul_32_8_n_46,
       const_mul_32_8_n_47, const_mul_32_8_n_48;
  assign out1[0] = in1[0];
  MXI2XL const_mul_32_8_g336(.A (const_mul_32_8_n_24), .B
       (const_mul_32_8_n_25), .S0 (const_mul_32_8_n_47), .Y (out1[9]));
  AOI21X1 const_mul_32_8_g338(.A0 (const_mul_32_8_n_19), .A1
       (const_mul_32_8_n_46), .B0 (const_mul_32_8_n_14), .Y
       (const_mul_32_8_n_48));
  AOI21X2 const_mul_32_8_g341(.A0 (const_mul_32_8_n_22), .A1
       (const_mul_32_8_n_44), .B0 (const_mul_32_8_n_23), .Y
       (const_mul_32_8_n_47));
  OAI21X2 const_mul_32_8_g343(.A0 (const_mul_32_8_n_33), .A1
       (const_mul_32_8_n_42), .B0 (const_mul_32_8_n_36), .Y
       (const_mul_32_8_n_46));
  OAI21X1 const_mul_32_8_g344(.A0 (const_mul_32_8_n_16), .A1
       (const_mul_32_8_n_42), .B0 (const_mul_32_8_n_18), .Y
       (const_mul_32_8_n_45));
  NAND2X1 const_mul_32_8_g345(.A (const_mul_32_8_n_39), .B
       (const_mul_32_8_n_8), .Y (const_mul_32_8_n_44));
  OAI2BB2XL const_mul_32_8_g347(.A0N (const_mul_32_8_n_38), .A1N
       (const_mul_32_8_n_31), .B0 (const_mul_32_8_n_38), .B1
       (const_mul_32_8_n_31), .Y (out1[3]));
  NOR2X2 const_mul_32_8_g350(.A (const_mul_32_8_n_1), .B
       (const_mul_32_8_n_41), .Y (const_mul_32_8_n_42));
  NOR3X2 const_mul_32_8_g351(.A (in1[2]), .B (const_mul_32_8_n_15), .C
       (const_mul_32_8_n_34), .Y (const_mul_32_8_n_41));
  MXI2XL const_mul_32_8_g352(.A (const_mul_32_8_n_11), .B (in1[2]), .S0
       (const_mul_32_8_n_34), .Y (out1[2]));
  AOI2BB1X1 const_mul_32_8_g353(.A0N (const_mul_32_8_n_28), .A1N
       (const_mul_32_8_n_36), .B0 (const_mul_32_8_n_35), .Y
       (const_mul_32_8_n_39));
  NAND2X1 const_mul_32_8_g354(.A (const_mul_32_8_n_11), .B
       (const_mul_32_8_n_20), .Y (const_mul_32_8_n_38));
  NOR2X1 const_mul_32_8_g355(.A (const_mul_32_8_n_28), .B
       (const_mul_32_8_n_33), .Y (const_mul_32_8_n_37));
  AOI2BB1X1 const_mul_32_8_g356(.A0N (const_mul_32_8_n_18), .A1N
       (const_mul_32_8_n_2), .B0 (const_mul_32_8_n_17), .Y
       (const_mul_32_8_n_36));
  OAI2BB1X1 const_mul_32_8_g357(.A0N (const_mul_32_8_n_13), .A1N
       (const_mul_32_8_n_14), .B0 (const_mul_32_8_n_21), .Y
       (const_mul_32_8_n_35));
  INVX1 const_mul_32_8_g358(.A (const_mul_32_8_n_20), .Y
       (const_mul_32_8_n_34));
  OR2X1 const_mul_32_8_g359(.A (const_mul_32_8_n_2), .B
       (const_mul_32_8_n_16), .Y (const_mul_32_8_n_33));
  NOR2X1 const_mul_32_8_g361(.A (const_mul_32_8_n_17), .B
       (const_mul_32_8_n_2), .Y (const_mul_32_8_n_32));
  NOR2X1 const_mul_32_8_g362(.A (const_mul_32_8_n_1), .B
       (const_mul_32_8_n_15), .Y (const_mul_32_8_n_31));
  NOR2BX1 const_mul_32_8_g364(.AN (const_mul_32_8_n_22), .B
       (const_mul_32_8_n_23), .Y (const_mul_32_8_n_30));
  NAND2BX1 const_mul_32_8_g366(.AN (const_mul_32_8_n_16), .B
       (const_mul_32_8_n_18), .Y (const_mul_32_8_n_29));
  NAND2X1 const_mul_32_8_g367(.A (const_mul_32_8_n_13), .B
       (const_mul_32_8_n_19), .Y (const_mul_32_8_n_28));
  NAND2X1 const_mul_32_8_g369(.A (const_mul_32_8_n_21), .B
       (const_mul_32_8_n_13), .Y (const_mul_32_8_n_27));
  NOR2BX1 const_mul_32_8_g371(.AN (const_mul_32_8_n_19), .B
       (const_mul_32_8_n_14), .Y (const_mul_32_8_n_26));
  INVX1 const_mul_32_8_g373(.A (const_mul_32_8_n_24), .Y
       (const_mul_32_8_n_25));
  XNOR2X1 const_mul_32_8_g374(.A (in1[9]), .B (in1[6]), .Y
       (const_mul_32_8_n_24));
  NOR2BX1 const_mul_32_8_g375(.AN (in1[5]), .B (in1[8]), .Y
       (const_mul_32_8_n_23));
  NAND2BX1 const_mul_32_8_g376(.AN (in1[5]), .B (in1[8]), .Y
       (const_mul_32_8_n_22));
  NAND2BX1 const_mul_32_8_g377(.AN (in1[7]), .B (in1[4]), .Y
       (const_mul_32_8_n_21));
  NOR2X2 const_mul_32_8_g378(.A (in1[1]), .B (in1[0]), .Y
       (const_mul_32_8_n_20));
  NAND2BX1 const_mul_32_8_g381(.AN (in1[3]), .B (in1[6]), .Y
       (const_mul_32_8_n_19));
  NAND2X4 const_mul_32_8_g382(.A (in1[1]), .B (const_mul_32_8_n_10), .Y
       (const_mul_32_8_n_18));
  NOR2X1 const_mul_32_8_g383(.A (const_mul_32_8_n_11), .B (in1[5]), .Y
       (const_mul_32_8_n_17));
  NOR2X1 const_mul_32_8_g384(.A (const_mul_32_8_n_10), .B (in1[1]), .Y
       (const_mul_32_8_n_16));
  NOR2X2 const_mul_32_8_g385(.A (in1[0]), .B (const_mul_32_8_n_12), .Y
       (const_mul_32_8_n_15));
  NOR2X1 const_mul_32_8_g386(.A (const_mul_32_8_n_12), .B (in1[6]), .Y
       (const_mul_32_8_n_14));
  NAND2X1 const_mul_32_8_g387(.A (in1[7]), .B (const_mul_32_8_n_10), .Y
       (const_mul_32_8_n_13));
  INVX1 const_mul_32_8_g388(.A (in1[3]), .Y (const_mul_32_8_n_12));
  INVX1 const_mul_32_8_g389(.A (in1[2]), .Y (const_mul_32_8_n_11));
  CLKINVX2 const_mul_32_8_g390(.A (in1[4]), .Y (const_mul_32_8_n_10));
  NAND2BX1 const_mul_32_8_g2(.AN (const_mul_32_8_n_42), .B
       (const_mul_32_8_n_37), .Y (const_mul_32_8_n_8));
  CLKXOR2X1 const_mul_32_8_g394(.A (const_mul_32_8_n_32), .B
       (const_mul_32_8_n_45), .Y (out1[5]));
  CLKXOR2X1 const_mul_32_8_g395(.A (const_mul_32_8_n_30), .B
       (const_mul_32_8_n_44), .Y (out1[8]));
  CLKXOR2X1 const_mul_32_8_g396(.A (const_mul_32_8_n_29), .B
       (const_mul_32_8_n_42), .Y (out1[4]));
  CLKXOR2X1 const_mul_32_8_g397(.A (const_mul_32_8_n_27), .B
       (const_mul_32_8_n_48), .Y (out1[7]));
  CLKXOR2X1 const_mul_32_8_g398(.A (const_mul_32_8_n_26), .B
       (const_mul_32_8_n_46), .Y (out1[6]));
  NOR2BX1 const_mul_32_8_g399(.AN (in1[5]), .B (in1[2]), .Y
       (const_mul_32_8_n_2));
  NOR2BX1 const_mul_32_8_g400(.AN (in1[0]), .B (in1[3]), .Y
       (const_mul_32_8_n_1));
  CLKXOR2X1 const_mul_32_8_g401(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
endmodule


