`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Add_11Sx2S_12S_4(in2, in1, out1);
  input [10:0] in2;
  input [1:0] in1;
  output [11:0] out1;
  wire [10:0] in2;
  wire [1:0] in1;
  wire [11:0] out1;
  wire add_35_2_n_0, add_35_2_n_1, add_35_2_n_2, add_35_2_n_3,
       add_35_2_n_4, add_35_2_n_5, add_35_2_n_6, add_35_2_n_7;
  wire add_35_2_n_8, add_35_2_n_9, add_35_2_n_10, add_35_2_n_11,
       add_35_2_n_12, add_35_2_n_13, add_35_2_n_14, add_35_2_n_15;
  wire add_35_2_n_16, add_35_2_n_18, add_35_2_n_19, add_35_2_n_20,
       add_35_2_n_21, add_35_2_n_22, add_35_2_n_23, add_35_2_n_24;
  wire add_35_2_n_25, add_35_2_n_26, add_35_2_n_28, add_35_2_n_29,
       add_35_2_n_30, add_35_2_n_32, add_35_2_n_33, add_35_2_n_35;
  wire add_35_2_n_37, add_35_2_n_38, add_35_2_n_39, add_35_2_n_41,
       add_35_2_n_43, add_35_2_n_44, add_35_2_n_46, add_35_2_n_48;
  wire add_35_2_n_49, add_35_2_n_52;
  INVX1 add_35_2_g344(.A (add_35_2_n_52), .Y (out1[10]));
  ADDFX1 add_35_2_g345(.A (add_35_2_n_48), .B (in1[1]), .CI (in2[10]),
       .CO (out1[11]), .S (add_35_2_n_52));
  INVX1 add_35_2_g346(.A (add_35_2_n_49), .Y (out1[9]));
  ADDFX1 add_35_2_g347(.A (add_35_2_n_46), .B (add_35_2_n_3), .CI
       (add_35_2_n_0), .CO (add_35_2_n_48), .S (add_35_2_n_49));
  XNOR2X1 add_35_2_g348(.A (add_35_2_n_24), .B (add_35_2_n_44), .Y
       (out1[7]));
  OA21X1 add_35_2_g349(.A0 (add_35_2_n_16), .A1 (add_35_2_n_43), .B0
       (add_35_2_n_11), .Y (add_35_2_n_46));
  XNOR2X1 add_35_2_g350(.A (add_35_2_n_25), .B (add_35_2_n_43), .Y
       (out1[8]));
  OAI21X1 add_35_2_g351(.A0 (add_35_2_n_8), .A1 (add_35_2_n_39), .B0
       (add_35_2_n_13), .Y (add_35_2_n_44));
  AOI211XL add_35_2_g352(.A0 (add_35_2_n_18), .A1 (add_35_2_n_26), .B0
       (add_35_2_n_41), .C0 (add_35_2_n_23), .Y (add_35_2_n_43));
  XNOR2X1 add_35_2_g353(.A (add_35_2_n_22), .B (add_35_2_n_39), .Y
       (out1[6]));
  OAI2BB1X1 add_35_2_g354(.A0N (add_35_2_n_18), .A1N (add_35_2_n_38),
       .B0 (add_35_2_n_10), .Y (add_35_2_n_41));
  XNOR2X1 add_35_2_g355(.A (add_35_2_n_21), .B (add_35_2_n_37), .Y
       (out1[5]));
  NOR2X1 add_35_2_g356(.A (add_35_2_n_26), .B (add_35_2_n_38), .Y
       (add_35_2_n_39));
  NOR2BX1 add_35_2_g357(.AN (add_35_2_n_35), .B (add_35_2_n_9), .Y
       (add_35_2_n_38));
  NOR2BX1 add_35_2_g358(.AN (add_35_2_n_7), .B (add_35_2_n_35), .Y
       (add_35_2_n_37));
  XNOR2X1 add_35_2_g359(.A (add_35_2_n_20), .B (add_35_2_n_33), .Y
       (out1[4]));
  NOR2X1 add_35_2_g360(.A (add_35_2_n_12), .B (add_35_2_n_33), .Y
       (add_35_2_n_35));
  INVX1 add_35_2_g361(.A (add_35_2_n_32), .Y (out1[3]));
  ADDFX1 add_35_2_g362(.A (add_35_2_n_29), .B (add_35_2_n_3), .CI
       (add_35_2_n_2), .CO (add_35_2_n_33), .S (add_35_2_n_32));
  INVX1 add_35_2_g363(.A (add_35_2_n_30), .Y (out1[2]));
  ADDFX1 add_35_2_g364(.A (add_35_2_n_28), .B (add_35_2_n_3), .CI
       (add_35_2_n_1), .CO (add_35_2_n_29), .S (add_35_2_n_30));
  OA21X1 add_35_2_g365(.A0 (add_35_2_n_4), .A1 (add_35_2_n_6), .B0
       (add_35_2_n_14), .Y (add_35_2_n_28));
  XNOR2X1 add_35_2_g366(.A (add_35_2_n_4), .B (add_35_2_n_19), .Y
       (out1[1]));
  OAI21X1 add_35_2_g367(.A0 (add_35_2_n_7), .A1 (add_35_2_n_9), .B0
       (add_35_2_n_15), .Y (add_35_2_n_26));
  NOR2BX1 add_35_2_g368(.AN (add_35_2_n_11), .B (add_35_2_n_16), .Y
       (add_35_2_n_25));
  NAND2BX1 add_35_2_g369(.AN (add_35_2_n_5), .B (add_35_2_n_10), .Y
       (add_35_2_n_24));
  NOR2X1 add_35_2_g370(.A (add_35_2_n_13), .B (add_35_2_n_5), .Y
       (add_35_2_n_23));
  NOR2BX1 add_35_2_g371(.AN (add_35_2_n_13), .B (add_35_2_n_8), .Y
       (add_35_2_n_22));
  NOR2BX1 add_35_2_g372(.AN (add_35_2_n_15), .B (add_35_2_n_9), .Y
       (add_35_2_n_21));
  NOR2BX1 add_35_2_g373(.AN (add_35_2_n_7), .B (add_35_2_n_12), .Y
       (add_35_2_n_20));
  NOR2BX1 add_35_2_g374(.AN (add_35_2_n_14), .B (add_35_2_n_6), .Y
       (add_35_2_n_19));
  NOR2X1 add_35_2_g375(.A (add_35_2_n_5), .B (add_35_2_n_8), .Y
       (add_35_2_n_18));
  XOR2XL add_35_2_g376(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NOR2X1 add_35_2_g377(.A (in2[8]), .B (in1[1]), .Y (add_35_2_n_16));
  NAND2X1 add_35_2_g378(.A (in2[5]), .B (in1[1]), .Y (add_35_2_n_15));
  NAND2X1 add_35_2_g379(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_14));
  NAND2X1 add_35_2_g380(.A (in2[6]), .B (in1[1]), .Y (add_35_2_n_13));
  NOR2X1 add_35_2_g381(.A (in2[4]), .B (in1[1]), .Y (add_35_2_n_12));
  NAND2X1 add_35_2_g382(.A (in2[8]), .B (in1[1]), .Y (add_35_2_n_11));
  NAND2X1 add_35_2_g383(.A (in2[7]), .B (in1[1]), .Y (add_35_2_n_10));
  NOR2X1 add_35_2_g384(.A (in2[5]), .B (in1[1]), .Y (add_35_2_n_9));
  NOR2X1 add_35_2_g385(.A (in2[6]), .B (in1[1]), .Y (add_35_2_n_8));
  NAND2X1 add_35_2_g386(.A (in2[4]), .B (in1[1]), .Y (add_35_2_n_7));
  NOR2X1 add_35_2_g387(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_6));
  NOR2X1 add_35_2_g388(.A (in2[7]), .B (in1[1]), .Y (add_35_2_n_5));
  NAND2X1 add_35_2_g389(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_4));
  INVX1 add_35_2_g390(.A (in1[1]), .Y (add_35_2_n_3));
  INVX1 add_35_2_g391(.A (in2[3]), .Y (add_35_2_n_2));
  INVX1 add_35_2_g392(.A (in2[2]), .Y (add_35_2_n_1));
  INVX1 add_35_2_g393(.A (in2[9]), .Y (add_35_2_n_0));
endmodule


