`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Add2i1s7_4(in1, out1);
  input [6:0] in1;
  output [7:0] out1;
  wire [6:0] in1;
  wire [7:0] out1;
  wire inc_add_33_2_1_n_1, inc_add_33_2_1_n_3, inc_add_33_2_1_n_5,
       inc_add_33_2_1_n_7, inc_add_33_2_1_n_9;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 inc_add_33_2_1_g50(.A (in1[6]), .B (inc_add_33_2_1_n_9), .Y
       (out1[6]));
  XNOR2X1 inc_add_33_2_1_g52(.A (in1[5]), .B (inc_add_33_2_1_n_7), .Y
       (out1[5]));
  NAND2BX1 inc_add_33_2_1_g53(.AN (inc_add_33_2_1_n_7), .B (in1[5]), .Y
       (inc_add_33_2_1_n_9));
  XNOR2X1 inc_add_33_2_1_g54(.A (in1[4]), .B (inc_add_33_2_1_n_5), .Y
       (out1[4]));
  NAND2BX1 inc_add_33_2_1_g55(.AN (inc_add_33_2_1_n_5), .B (in1[4]), .Y
       (inc_add_33_2_1_n_7));
  XNOR2X1 inc_add_33_2_1_g56(.A (in1[3]), .B (inc_add_33_2_1_n_3), .Y
       (out1[3]));
  NAND2BX1 inc_add_33_2_1_g57(.AN (inc_add_33_2_1_n_3), .B (in1[3]), .Y
       (inc_add_33_2_1_n_5));
  XNOR2X1 inc_add_33_2_1_g58(.A (in1[2]), .B (inc_add_33_2_1_n_1), .Y
       (out1[2]));
  NAND2BX1 inc_add_33_2_1_g59(.AN (inc_add_33_2_1_n_1), .B (in1[2]), .Y
       (inc_add_33_2_1_n_3));
  XOR2XL inc_add_33_2_1_g60(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2X1 inc_add_33_2_1_g61(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_33_2_1_n_1));
  AND2X1 inc_add_33_2_1_g2(.A (in1[6]), .B (inc_add_33_2_1_n_9), .Y
       (out1[7]));
endmodule


