`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Add_11Sx2S_12S_1(in2, in1, out1);
  input [10:0] in2;
  input [1:0] in1;
  output [11:0] out1;
  wire [10:0] in2;
  wire [1:0] in1;
  wire [11:0] out1;
  wire add_35_2_n_0, add_35_2_n_9, add_35_2_n_10, add_35_2_n_11,
       add_35_2_n_12, add_35_2_n_13, add_35_2_n_14, add_35_2_n_15;
  wire add_35_2_n_16, add_35_2_n_17, add_35_2_n_18, add_35_2_n_19,
       add_35_2_n_20, add_35_2_n_21, add_35_2_n_22, add_35_2_n_23;
  wire add_35_2_n_24, add_35_2_n_25, add_35_2_n_26, add_35_2_n_27,
       add_35_2_n_28, add_35_2_n_29, add_35_2_n_30, add_35_2_n_31;
  wire add_35_2_n_32, add_35_2_n_33, add_35_2_n_34, add_35_2_n_35,
       add_35_2_n_36, add_35_2_n_37, add_35_2_n_38, add_35_2_n_39;
  wire add_35_2_n_40, add_35_2_n_41, add_35_2_n_42, add_35_2_n_43,
       add_35_2_n_44, add_35_2_n_45, add_35_2_n_46, add_35_2_n_47;
  wire add_35_2_n_48, add_35_2_n_49, add_35_2_n_50, add_35_2_n_51,
       add_35_2_n_52, add_35_2_n_53, add_35_2_n_54, add_35_2_n_55;
  wire add_35_2_n_56, add_35_2_n_57, add_35_2_n_58, add_35_2_n_60,
       add_35_2_n_61, add_35_2_n_62, add_35_2_n_63, add_35_2_n_65;
  wire add_35_2_n_66, add_35_2_n_67, add_35_2_n_68, add_35_2_n_69,
       add_35_2_n_70, add_35_2_n_71, add_35_2_n_72, add_35_2_n_73;
  wire add_35_2_n_75, add_35_2_n_76, n_92, n_93;
  MXI2XL add_35_2_g244(.A (add_35_2_n_45), .B (add_35_2_n_44), .S0
       (add_35_2_n_76), .Y (out1[10]));
  MXI2XL add_35_2_g245(.A (add_35_2_n_35), .B (add_35_2_n_34), .S0
       (add_35_2_n_75), .Y (out1[9]));
  AOI2BB1XL add_35_2_g246(.A0N (add_35_2_n_48), .A1N (add_35_2_n_73),
       .B0 (add_35_2_n_53), .Y (add_35_2_n_76));
  AOI2BB1XL add_35_2_g247(.A0N (add_35_2_n_15), .A1N (add_35_2_n_73),
       .B0 (add_35_2_n_14), .Y (add_35_2_n_75));
  AOI2BB1XL add_35_2_g248(.A0N (add_35_2_n_56), .A1N (add_35_2_n_73),
       .B0 (add_35_2_n_62), .Y (out1[11]));
  NOR2X2 add_35_2_g253(.A (add_35_2_n_60), .B (add_35_2_n_69), .Y
       (add_35_2_n_73));
  AOI21X1 add_35_2_g254(.A0 (add_35_2_n_37), .A1 (add_35_2_n_67), .B0
       (add_35_2_n_50), .Y (add_35_2_n_72));
  AOI21X1 add_35_2_g255(.A0 (add_35_2_n_32), .A1 (add_35_2_n_67), .B0
       (add_35_2_n_26), .Y (add_35_2_n_71));
  NOR2X1 add_35_2_g258(.A (add_35_2_n_61), .B (add_35_2_n_68), .Y
       (add_35_2_n_70));
  NOR2X2 add_35_2_g259(.A (add_35_2_n_55), .B (add_35_2_n_66), .Y
       (add_35_2_n_69));
  NOR2X1 add_35_2_g260(.A (add_35_2_n_54), .B (add_35_2_n_66), .Y
       (add_35_2_n_68));
  INVX2 add_35_2_g261(.A (add_35_2_n_66), .Y (add_35_2_n_67));
  NOR2X2 add_35_2_g262(.A (add_35_2_n_51), .B (add_35_2_n_63), .Y
       (add_35_2_n_66));
  OAI21X1 add_35_2_g263(.A0 (add_35_2_n_18), .A1 (n_92), .B0
       (add_35_2_n_22), .Y (add_35_2_n_65));
  XOR2XL add_35_2_g264(.A (add_35_2_n_49), .B (n_92), .Y (out1[2]));
  NOR2X2 add_35_2_g265(.A (add_35_2_n_40), .B (n_93), .Y
       (add_35_2_n_63));
  OAI2BB1X1 add_35_2_g266(.A0N (add_35_2_n_29), .A1N (add_35_2_n_53),
       .B0 (add_35_2_n_16), .Y (add_35_2_n_62));
  OAI2BB1X1 add_35_2_g267(.A0N (add_35_2_n_24), .A1N (add_35_2_n_50),
       .B0 (add_35_2_n_20), .Y (add_35_2_n_61));
  NAND2X1 add_35_2_g268(.A (add_35_2_n_52), .B (add_35_2_n_58), .Y
       (add_35_2_n_60));
  NOR2X2 add_35_2_g269(.A (add_35_2_n_0), .B (add_35_2_n_57), .Y
       (n_93));
  NAND2X1 add_35_2_g271(.A (add_35_2_n_36), .B (add_35_2_n_50), .Y
       (add_35_2_n_58));
  NOR2X2 add_35_2_g272(.A (add_35_2_n_9), .B (add_35_2_n_10), .Y
       (add_35_2_n_57));
  NAND2X1 add_35_2_g273(.A (add_35_2_n_29), .B (add_35_2_n_47), .Y
       (add_35_2_n_56));
  NAND2X1 add_35_2_g274(.A (add_35_2_n_36), .B (add_35_2_n_37), .Y
       (add_35_2_n_55));
  NAND2X1 add_35_2_g275(.A (add_35_2_n_24), .B (add_35_2_n_37), .Y
       (add_35_2_n_54));
  OAI21X1 add_35_2_g276(.A0 (add_35_2_n_13), .A1 (add_35_2_n_17), .B0
       (add_35_2_n_27), .Y (add_35_2_n_53));
  OA21X1 add_35_2_g277(.A0 (add_35_2_n_20), .A1 (add_35_2_n_28), .B0
       (add_35_2_n_12), .Y (add_35_2_n_52));
  OAI21X1 add_35_2_g278(.A0 (add_35_2_n_22), .A1 (add_35_2_n_11), .B0
       (add_35_2_n_19), .Y (add_35_2_n_51));
  OAI21X2 add_35_2_g279(.A0 (add_35_2_n_25), .A1 (add_35_2_n_21), .B0
       (add_35_2_n_30), .Y (add_35_2_n_50));
  NAND2BX1 add_35_2_g281(.AN (add_35_2_n_18), .B (add_35_2_n_22), .Y
       (add_35_2_n_49));
  INVX1 add_35_2_g282(.A (add_35_2_n_47), .Y (add_35_2_n_48));
  NOR2X1 add_35_2_g283(.A (add_35_2_n_17), .B (add_35_2_n_15), .Y
       (add_35_2_n_47));
  NOR2X1 add_35_2_g285(.A (add_35_2_n_14), .B (add_35_2_n_15), .Y
       (add_35_2_n_46));
  INVX1 add_35_2_g286(.A (add_35_2_n_44), .Y (add_35_2_n_45));
  NAND2X1 add_35_2_g287(.A (add_35_2_n_29), .B (add_35_2_n_16), .Y
       (add_35_2_n_44));
  NAND2X1 add_35_2_g289(.A (add_35_2_n_20), .B (add_35_2_n_24), .Y
       (add_35_2_n_43));
  NAND2X1 add_35_2_g291(.A (add_35_2_n_25), .B (add_35_2_n_32), .Y
       (add_35_2_n_42));
  NAND2BX1 add_35_2_g293(.AN (add_35_2_n_21), .B (add_35_2_n_30), .Y
       (add_35_2_n_41));
  OR2XL add_35_2_g294(.A (add_35_2_n_11), .B (add_35_2_n_18), .Y
       (add_35_2_n_40));
  NOR2BX1 add_35_2_g296(.AN (add_35_2_n_12), .B (add_35_2_n_28), .Y
       (add_35_2_n_39));
  NOR2BX1 add_35_2_g298(.AN (add_35_2_n_19), .B (add_35_2_n_11), .Y
       (add_35_2_n_38));
  NOR2X1 add_35_2_g299(.A (add_35_2_n_21), .B (add_35_2_n_31), .Y
       (add_35_2_n_37));
  NOR2X1 add_35_2_g300(.A (add_35_2_n_28), .B (add_35_2_n_23), .Y
       (add_35_2_n_36));
  INVX1 add_35_2_g301(.A (add_35_2_n_34), .Y (add_35_2_n_35));
  NAND2BX1 add_35_2_g302(.AN (add_35_2_n_17), .B (add_35_2_n_27), .Y
       (add_35_2_n_34));
  NOR2X1 add_35_2_g303(.A (add_35_2_n_0), .B (add_35_2_n_10), .Y
       (add_35_2_n_33));
  INVX1 add_35_2_g305(.A (add_35_2_n_31), .Y (add_35_2_n_32));
  NOR2X1 add_35_2_g306(.A (in2[4]), .B (in1[1]), .Y (add_35_2_n_31));
  NAND2X1 add_35_2_g307(.A (in2[5]), .B (in1[1]), .Y (add_35_2_n_30));
  NAND2X1 add_35_2_g308(.A (in2[10]), .B (in1[1]), .Y (add_35_2_n_29));
  NOR2X1 add_35_2_g309(.A (in2[7]), .B (in1[1]), .Y (add_35_2_n_28));
  NAND2X1 add_35_2_g310(.A (in2[9]), .B (in1[1]), .Y (add_35_2_n_27));
  INVX1 add_35_2_g311(.A (add_35_2_n_25), .Y (add_35_2_n_26));
  NAND2X2 add_35_2_g312(.A (in2[4]), .B (in1[1]), .Y (add_35_2_n_25));
  INVX1 add_35_2_g313(.A (add_35_2_n_23), .Y (add_35_2_n_24));
  NOR2X1 add_35_2_g314(.A (in2[6]), .B (in1[1]), .Y (add_35_2_n_23));
  NAND2X2 add_35_2_g315(.A (in2[2]), .B (in1[1]), .Y (add_35_2_n_22));
  NOR2X2 add_35_2_g316(.A (in2[5]), .B (in1[1]), .Y (add_35_2_n_21));
  NAND2X1 add_35_2_g317(.A (in2[6]), .B (in1[1]), .Y (add_35_2_n_20));
  NAND2X1 add_35_2_g318(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_19));
  NOR2X2 add_35_2_g319(.A (in2[2]), .B (in1[1]), .Y (add_35_2_n_18));
  NOR2X1 add_35_2_g320(.A (in2[9]), .B (in1[1]), .Y (add_35_2_n_17));
  OR2X1 add_35_2_g321(.A (in2[10]), .B (in1[1]), .Y (add_35_2_n_16));
  NOR2X1 add_35_2_g322(.A (in2[8]), .B (in1[1]), .Y (add_35_2_n_15));
  INVX1 add_35_2_g324(.A (add_35_2_n_13), .Y (add_35_2_n_14));
  NAND2X1 add_35_2_g325(.A (in2[8]), .B (in1[1]), .Y (add_35_2_n_13));
  NAND2X1 add_35_2_g326(.A (in2[7]), .B (in1[1]), .Y (add_35_2_n_12));
  NOR2X8 add_35_2_g327(.A (in2[3]), .B (in1[1]), .Y (add_35_2_n_11));
  NOR2X4 add_35_2_g328(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_10));
  NAND2X4 add_35_2_g329(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_9));
  XNOR2X1 add_35_2_g2(.A (add_35_2_n_9), .B (add_35_2_n_33), .Y
       (out1[1]));
  XNOR2X1 add_35_2_g333(.A (add_35_2_n_46), .B (add_35_2_n_73), .Y
       (out1[8]));
  CLKXOR2X1 add_35_2_g334(.A (add_35_2_n_43), .B (add_35_2_n_72), .Y
       (out1[6]));
  XNOR2X1 add_35_2_g335(.A (add_35_2_n_42), .B (add_35_2_n_67), .Y
       (out1[4]));
  CLKXOR2X1 add_35_2_g336(.A (add_35_2_n_41), .B (add_35_2_n_71), .Y
       (out1[5]));
  XNOR2X1 add_35_2_g337(.A (add_35_2_n_39), .B (add_35_2_n_70), .Y
       (out1[7]));
  CLKXOR2X1 add_35_2_g338(.A (add_35_2_n_38), .B (add_35_2_n_65), .Y
       (out1[3]));
  CLKXOR2X1 add_35_2_g339(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  CLKAND2X6 add_35_2_g340(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_0));
  BUFX3 fopt(.A (n_93), .Y (n_92));
endmodule


