`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Add2i1s11_4(in1, out1);
  input [10:0] in1;
  output [11:0] out1;
  wire [10:0] in1;
  wire [11:0] out1;
  wire inc_add_33_2_1_n_1, inc_add_33_2_1_n_3, inc_add_33_2_1_n_5,
       inc_add_33_2_1_n_7, inc_add_33_2_1_n_9, inc_add_33_2_1_n_11,
       inc_add_33_2_1_n_13, inc_add_33_2_1_n_15;
  wire inc_add_33_2_1_n_17;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 inc_add_33_2_1_g78(.A (in1[10]), .B (inc_add_33_2_1_n_17), .Y
       (out1[10]));
  XNOR2X1 inc_add_33_2_1_g80(.A (in1[9]), .B (inc_add_33_2_1_n_15), .Y
       (out1[9]));
  NAND2BX1 inc_add_33_2_1_g81(.AN (inc_add_33_2_1_n_15), .B (in1[9]),
       .Y (inc_add_33_2_1_n_17));
  XNOR2X1 inc_add_33_2_1_g82(.A (in1[8]), .B (inc_add_33_2_1_n_13), .Y
       (out1[8]));
  NAND2BX1 inc_add_33_2_1_g83(.AN (inc_add_33_2_1_n_13), .B (in1[8]),
       .Y (inc_add_33_2_1_n_15));
  XNOR2X1 inc_add_33_2_1_g84(.A (in1[7]), .B (inc_add_33_2_1_n_11), .Y
       (out1[7]));
  NAND2BX1 inc_add_33_2_1_g85(.AN (inc_add_33_2_1_n_11), .B (in1[7]),
       .Y (inc_add_33_2_1_n_13));
  XNOR2X1 inc_add_33_2_1_g86(.A (in1[6]), .B (inc_add_33_2_1_n_9), .Y
       (out1[6]));
  NAND2BX1 inc_add_33_2_1_g87(.AN (inc_add_33_2_1_n_9), .B (in1[6]), .Y
       (inc_add_33_2_1_n_11));
  XNOR2X1 inc_add_33_2_1_g88(.A (in1[5]), .B (inc_add_33_2_1_n_7), .Y
       (out1[5]));
  NAND2BX1 inc_add_33_2_1_g89(.AN (inc_add_33_2_1_n_7), .B (in1[5]), .Y
       (inc_add_33_2_1_n_9));
  XNOR2X1 inc_add_33_2_1_g90(.A (in1[4]), .B (inc_add_33_2_1_n_5), .Y
       (out1[4]));
  NAND2BX1 inc_add_33_2_1_g91(.AN (inc_add_33_2_1_n_5), .B (in1[4]), .Y
       (inc_add_33_2_1_n_7));
  XNOR2X1 inc_add_33_2_1_g92(.A (in1[3]), .B (inc_add_33_2_1_n_3), .Y
       (out1[3]));
  NAND2BX1 inc_add_33_2_1_g93(.AN (inc_add_33_2_1_n_3), .B (in1[3]), .Y
       (inc_add_33_2_1_n_5));
  XNOR2X1 inc_add_33_2_1_g94(.A (in1[2]), .B (inc_add_33_2_1_n_1), .Y
       (out1[2]));
  NAND2BX1 inc_add_33_2_1_g95(.AN (inc_add_33_2_1_n_1), .B (in1[2]), .Y
       (inc_add_33_2_1_n_3));
  XOR2XL inc_add_33_2_1_g96(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2X1 inc_add_33_2_1_g97(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_33_2_1_n_1));
  AND2X1 inc_add_33_2_1_g2(.A (in1[10]), .B (inc_add_33_2_1_n_17), .Y
       (out1[11]));
endmodule


