`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Lti64s8_4(in1, out1);
  input [7:0] in1;
  output out1;
  wire [7:0] in1;
  wire out1;
  NAND2BXL gt_31_57_g155(.AN (in1[7]), .B (in1[6]), .Y (out1));
endmodule


