`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Mul_9Ux3U_9U_1(in2, in1, out1);
  input [8:0] in2;
  input [2:0] in1;
  output [8:0] out1;
  wire [8:0] in2;
  wire [2:0] in1;
  wire [8:0] out1;
  wire mul_34_8_n_1, mul_34_8_n_3, mul_34_8_n_4, mul_34_8_n_5,
       mul_34_8_n_6, mul_34_8_n_8, mul_34_8_n_14, mul_34_8_n_15;
  wire mul_34_8_n_16, mul_34_8_n_17, mul_34_8_n_20, mul_34_8_n_21,
       mul_34_8_n_22, mul_34_8_n_25, mul_34_8_n_26, mul_34_8_n_28;
  wire mul_34_8_n_29, mul_34_8_n_30, mul_34_8_n_31, mul_34_8_n_33,
       mul_34_8_n_34, mul_34_8_n_36, mul_34_8_n_37, mul_34_8_n_38;
  wire mul_34_8_n_39, mul_34_8_n_40, mul_34_8_n_42, mul_34_8_n_43,
       mul_34_8_n_44, mul_34_8_n_45, mul_34_8_n_46, mul_34_8_n_47;
  wire mul_34_8_n_48, mul_34_8_n_49, mul_34_8_n_52, mul_34_8_n_53,
       mul_34_8_n_54, mul_34_8_n_55, mul_34_8_n_56, mul_34_8_n_57;
  wire mul_34_8_n_58, mul_34_8_n_59, mul_34_8_n_60, mul_34_8_n_61,
       mul_34_8_n_62, mul_34_8_n_63, mul_34_8_n_64, mul_34_8_n_65;
  wire mul_34_8_n_66, mul_34_8_n_67, mul_34_8_n_68, mul_34_8_n_69,
       mul_34_8_n_70, mul_34_8_n_71, mul_34_8_n_72, mul_34_8_n_73;
  wire mul_34_8_n_74, mul_34_8_n_75, mul_34_8_n_76, mul_34_8_n_77,
       mul_34_8_n_78, mul_34_8_n_79, mul_34_8_n_81, mul_34_8_n_82;
  wire mul_34_8_n_83, mul_34_8_n_84, mul_34_8_n_85, mul_34_8_n_87,
       mul_34_8_n_88, mul_34_8_n_89, mul_34_8_n_90, mul_34_8_n_91;
  wire mul_34_8_n_92, mul_34_8_n_93, mul_34_8_n_94, mul_34_8_n_95,
       mul_34_8_n_96, mul_34_8_n_97, mul_34_8_n_98, mul_34_8_n_99;
  wire mul_34_8_n_100, mul_34_8_n_101, mul_34_8_n_102, mul_34_8_n_103,
       mul_34_8_n_104, mul_34_8_n_105, mul_34_8_n_106, mul_34_8_n_107;
  wire mul_34_8_n_108, mul_34_8_n_109, mul_34_8_n_110, mul_34_8_n_111,
       n_125, n_126, n_127, n_128;
  wire n_129, n_158, n_159, n_160, n_161, n_163, n_164, n_166;
  wire n_167, n_168, n_169, n_170, n_172, n_173, n_175, n_176;
  wire n_180, n_181, n_182, n_184, n_185, n_187;
  MXI2XL mul_34_8_g750(.A (mul_34_8_n_92), .B (mul_34_8_n_93), .S0
       (mul_34_8_n_111), .Y (out1[8]));
  AOI21X1 mul_34_8_g754(.A0 (mul_34_8_n_100), .A1 (mul_34_8_n_108), .B0
       (mul_34_8_n_105), .Y (mul_34_8_n_111));
  OAI21X1 mul_34_8_g755(.A0 (mul_34_8_n_91), .A1 (mul_34_8_n_15), .B0
       (mul_34_8_n_101), .Y (mul_34_8_n_110));
  NAND2X1 mul_34_8_g756(.A (n_129), .B (mul_34_8_n_15), .Y
       (mul_34_8_n_109));
  INVX1 mul_34_8_g759(.A (mul_34_8_n_15), .Y (mul_34_8_n_108));
  NOR2X1 mul_34_8_g761(.A (mul_34_8_n_75), .B (mul_34_8_n_106), .Y
       (mul_34_8_n_107));
  INVX1 mul_34_8_g762(.A (mul_34_8_n_6), .Y (mul_34_8_n_106));
  NAND2X1 mul_34_8_g764(.A (mul_34_8_n_102), .B (mul_34_8_n_104), .Y
       (mul_34_8_n_105));
  NAND2BX1 mul_34_8_g766(.AN (n_127), .B (mul_34_8_n_100), .Y
       (mul_34_8_n_104));
  NAND2X1 mul_34_8_g767(.A (mul_34_8_n_70), .B (mul_34_8_n_94), .Y
       (mul_34_8_n_103));
  AOI21X1 mul_34_8_g768(.A0 (mul_34_8_n_84), .A1 (mul_34_8_n_88), .B0
       (mul_34_8_n_8), .Y (mul_34_8_n_102));
  AOI21X1 mul_34_8_g769(.A0 (mul_34_8_n_90), .A1 (n_128), .B0
       (mul_34_8_n_88), .Y (mul_34_8_n_101));
  NOR2X2 mul_34_8_g770(.A (mul_34_8_n_85), .B (mul_34_8_n_91), .Y
       (mul_34_8_n_100));
  NOR2X2 mul_34_8_g771(.A (mul_34_8_n_75), .B (mul_34_8_n_89), .Y
       (mul_34_8_n_99));
  NOR2X1 mul_34_8_g773(.A (mul_34_8_n_8), .B (mul_34_8_n_85), .Y
       (mul_34_8_n_98));
  NOR2X1 mul_34_8_g775(.A (mul_34_8_n_88), .B (mul_34_8_n_91), .Y
       (mul_34_8_n_97));
  NOR2BX1 mul_34_8_g777(.AN (n_129), .B (mul_34_8_n_89), .Y
       (mul_34_8_n_96));
  AOI21X1 mul_34_8_g778(.A0 (mul_34_8_n_69), .A1 (mul_34_8_n_67), .B0
       (mul_34_8_n_68), .Y (mul_34_8_n_95));
  NAND2BX1 mul_34_8_g779(.AN (mul_34_8_n_68), .B (mul_34_8_n_83), .Y
       (mul_34_8_n_94));
  INVX1 mul_34_8_g781(.A (mul_34_8_n_92), .Y (mul_34_8_n_93));
  XNOR2X1 mul_34_8_g782(.A (mul_34_8_n_71), .B (mul_34_8_n_79), .Y
       (mul_34_8_n_92));
  INVX1 mul_34_8_g783(.A (mul_34_8_n_90), .Y (mul_34_8_n_91));
  NAND2X2 mul_34_8_g784(.A (mul_34_8_n_5), .B (mul_34_8_n_77), .Y
       (mul_34_8_n_90));
  NOR2X1 mul_34_8_g785(.A (mul_34_8_n_74), .B (mul_34_8_n_78), .Y
       (mul_34_8_n_89));
  NOR2X1 mul_34_8_g787(.A (mul_34_8_n_5), .B (mul_34_8_n_77), .Y
       (mul_34_8_n_88));
  NAND2X1 mul_34_8_g789(.A (mul_34_8_n_74), .B (mul_34_8_n_78), .Y
       (mul_34_8_n_87));
  INVX1 mul_34_8_g790(.A (mul_34_8_n_84), .Y (mul_34_8_n_85));
  NAND2X2 mul_34_8_g791(.A (mul_34_8_n_4), .B (mul_34_8_n_76), .Y
       (mul_34_8_n_84));
  NAND2X1 mul_34_8_g792(.A (mul_34_8_n_69), .B (mul_34_8_n_67), .Y
       (mul_34_8_n_83));
  NAND2BX1 mul_34_8_g797(.AN (mul_34_8_n_73), .B (mul_34_8_n_70), .Y
       (mul_34_8_n_82));
  NOR2BX1 mul_34_8_g798(.AN (mul_34_8_n_67), .B (mul_34_8_n_68), .Y
       (mul_34_8_n_81));
  NOR2BXL mul_34_8_g799(.AN (mul_34_8_n_72), .B (mul_34_8_n_69), .Y
       (out1[1]));
  XNOR2X1 mul_34_8_g800(.A (mul_34_8_n_58), .B (mul_34_8_n_65), .Y
       (mul_34_8_n_79));
  XNOR2X1 mul_34_8_g801(.A (mul_34_8_n_60), .B (mul_34_8_n_66), .Y
       (mul_34_8_n_78));
  CLKXOR2X1 mul_34_8_g802(.A (mul_34_8_n_54), .B (mul_34_8_n_62), .Y
       (mul_34_8_n_77));
  CLKXOR2X1 mul_34_8_g803(.A (mul_34_8_n_59), .B (mul_34_8_n_63), .Y
       (mul_34_8_n_76));
  XNOR2X1 mul_34_8_g804(.A (mul_34_8_n_53), .B (mul_34_8_n_61), .Y
       (mul_34_8_n_75));
  NOR2X1 mul_34_8_g805(.A (mul_34_8_n_61), .B (mul_34_8_n_53), .Y
       (mul_34_8_n_74));
  NOR2X1 mul_34_8_g808(.A (mul_34_8_n_64), .B (mul_34_8_n_57), .Y
       (mul_34_8_n_73));
  NAND2X1 mul_34_8_g809(.A (mul_34_8_n_40), .B (mul_34_8_n_55), .Y
       (mul_34_8_n_72));
  NOR2BX1 mul_34_8_g810(.AN (mul_34_8_n_59), .B (mul_34_8_n_63), .Y
       (mul_34_8_n_71));
  NAND2X1 mul_34_8_g811(.A (mul_34_8_n_64), .B (mul_34_8_n_57), .Y
       (mul_34_8_n_70));
  NOR2X2 mul_34_8_g813(.A (mul_34_8_n_40), .B (mul_34_8_n_55), .Y
       (mul_34_8_n_69));
  NOR2X1 mul_34_8_g814(.A (mul_34_8_n_48), .B (mul_34_8_n_56), .Y
       (mul_34_8_n_68));
  NAND2X1 mul_34_8_g815(.A (mul_34_8_n_48), .B (mul_34_8_n_56), .Y
       (mul_34_8_n_67));
  NOR2X1 mul_34_8_g817(.A (mul_34_8_n_49), .B (mul_34_8_n_52), .Y
       (mul_34_8_n_66));
  AOI22X1 mul_34_8_g818(.A0 (in2[5]), .A1 (n_160), .B0 (in2[6]), .B1
       (mul_34_8_n_34), .Y (mul_34_8_n_65));
  AOI2BB1X1 mul_34_8_g819(.A0N (mul_34_8_n_17), .A1N (n_161), .B0
       (mul_34_8_n_14), .Y (mul_34_8_n_64));
  AOI22X1 mul_34_8_g820(.A0 (in2[4]), .A1 (n_159), .B0 (in2[5]), .B1
       (mul_34_8_n_34), .Y (mul_34_8_n_63));
  AOI22X1 mul_34_8_g822(.A0 (in2[3]), .A1 (n_159), .B0 (in2[4]), .B1
       (mul_34_8_n_34), .Y (mul_34_8_n_62));
  AOI22X1 mul_34_8_g823(.A0 (in2[1]), .A1 (n_159), .B0 (in2[2]), .B1
       (mul_34_8_n_34), .Y (mul_34_8_n_61));
  OAI2BB1X1 mul_34_8_g824(.A0N (mul_34_8_n_33), .A1N (n_164), .B0
       (mul_34_8_n_45), .Y (mul_34_8_n_60));
  OAI2BB1X1 mul_34_8_g825(.A0N (mul_34_8_n_30), .A1N (n_164), .B0
       (mul_34_8_n_44), .Y (mul_34_8_n_59));
  AOI22X1 mul_34_8_g826(.A0 (n_126), .A1 (n_163), .B0 (n_180), .B1
       (mul_34_8_n_29), .Y (mul_34_8_n_58));
  AOI21X1 mul_34_8_g827(.A0 (mul_34_8_n_39), .A1 (n_163), .B0
       (mul_34_8_n_42), .Y (mul_34_8_n_57));
  AOI21X2 mul_34_8_g828(.A0 (mul_34_8_n_36), .A1 (n_164), .B0
       (mul_34_8_n_43), .Y (mul_34_8_n_56));
  AOI21X2 mul_34_8_g829(.A0 (n_164), .A1 (mul_34_8_n_37), .B0
       (mul_34_8_n_47), .Y (mul_34_8_n_55));
  OAI2BB1X1 mul_34_8_g830(.A0N (mul_34_8_n_1), .A1N (n_164), .B0
       (mul_34_8_n_46), .Y (mul_34_8_n_54));
  AOI21X1 mul_34_8_g831(.A0 (mul_34_8_n_31), .A1 (n_164), .B0
       (mul_34_8_n_3), .Y (mul_34_8_n_53));
  NOR2BX2 mul_34_8_g832(.AN (in2[2]), .B (n_158), .Y (mul_34_8_n_52));
  NOR2BX4 mul_34_8_g834(.AN (in1[2]), .B (mul_34_8_n_34), .Y (n_159));
  AND2X1 mul_34_8_g835(.A (in2[3]), .B (mul_34_8_n_34), .Y
       (mul_34_8_n_49));
  NAND2X1 mul_34_8_g836(.A (in2[0]), .B (mul_34_8_n_34), .Y
       (mul_34_8_n_48));
  NOR2X1 mul_34_8_g840(.A (n_185), .B (n_125), .Y (mul_34_8_n_47));
  NAND2X1 mul_34_8_g841(.A (n_182), .B (mul_34_8_n_30), .Y
       (mul_34_8_n_46));
  NAND2X1 mul_34_8_g842(.A (n_182), .B (mul_34_8_n_1), .Y
       (mul_34_8_n_45));
  NAND2X1 mul_34_8_g843(.A (n_182), .B (n_126), .Y (mul_34_8_n_44));
  NOR2X1 mul_34_8_g844(.A (n_184), .B (mul_34_8_n_38), .Y
       (mul_34_8_n_43));
  AND2XL mul_34_8_g845(.A (n_180), .B (mul_34_8_n_31), .Y
       (mul_34_8_n_42));
  NOR2X6 mul_34_8_g846(.A (n_182), .B (mul_34_8_n_28), .Y (n_164));
  NAND2X1 mul_34_8_g847(.A (n_168), .B (mul_34_8_n_22), .Y
       (mul_34_8_n_40));
  INVX1 mul_34_8_g849(.A (mul_34_8_n_38), .Y (mul_34_8_n_39));
  MXI2XL mul_34_8_g850(.A (in1[1]), .B (n_172), .S0 (in2[2]), .Y
       (mul_34_8_n_38));
  MXI2XL mul_34_8_g851(.A (mul_34_8_n_17), .B (in2[0]), .S0 (in1[1]),
       .Y (mul_34_8_n_37));
  INVX1 mul_34_8_g852(.A (n_125), .Y (mul_34_8_n_36));
  NAND2X8 mul_34_8_g854(.A (mul_34_8_n_25), .B (mul_34_8_n_26), .Y
       (mul_34_8_n_34));
  MXI2XL mul_34_8_g856(.A (n_170), .B (in1[1]), .S0 (in2[4]), .Y
       (mul_34_8_n_33));
  MXI2XL mul_34_8_g858(.A (n_170), .B (n_169), .S0 (in2[3]), .Y
       (mul_34_8_n_31));
  MXI2XL mul_34_8_g859(.A (n_172), .B (in1[1]), .S0 (in2[6]), .Y
       (mul_34_8_n_30));
  MXI2XL mul_34_8_g860(.A (n_167), .B (n_166), .S0 (in2[8]), .Y
       (mul_34_8_n_29));
  NOR2X2 mul_34_8_g861(.A (mul_34_8_n_20), .B (mul_34_8_n_21), .Y
       (mul_34_8_n_28));
  NAND2X6 mul_34_8_g864(.A (in1[1]), .B (mul_34_8_n_16), .Y
       (mul_34_8_n_26));
  NAND2X6 mul_34_8_g865(.A (in1[2]), .B (n_175), .Y (mul_34_8_n_25));
  INVX1 mul_34_8_g868(.A (mul_34_8_n_22), .Y (out1[0]));
  NAND2X1 mul_34_8_g869(.A (in2[0]), .B (n_182), .Y (mul_34_8_n_22));
  NOR2X2 mul_34_8_g870(.A (in1[1]), .B (n_187), .Y (mul_34_8_n_21));
  NOR2X2 mul_34_8_g871(.A (in1[0]), .B (n_176), .Y (mul_34_8_n_20));
  INVX1 mul_34_8_g874(.A (in2[0]), .Y (mul_34_8_n_17));
  CLKINVX4 mul_34_8_g878(.A (in1[2]), .Y (mul_34_8_n_16));
  NAND2X2 mul_34_8_g879(.A (mul_34_8_n_6), .B (mul_34_8_n_99), .Y
       (mul_34_8_n_15));
  AND2X1 mul_34_8_g2(.A (in2[1]), .B (mul_34_8_n_34), .Y
       (mul_34_8_n_14));
  XOR2XL mul_34_8_g880(.A (mul_34_8_n_98), .B (mul_34_8_n_110), .Y
       (out1[7]));
  CLKXOR2X1 mul_34_8_g881(.A (mul_34_8_n_97), .B (mul_34_8_n_109), .Y
       (out1[6]));
  CLKXOR2X1 mul_34_8_g882(.A (mul_34_8_n_96), .B (mul_34_8_n_107), .Y
       (out1[5]));
  CLKXOR2X1 mul_34_8_g883(.A (mul_34_8_n_75), .B (mul_34_8_n_106), .Y
       (out1[4]));
  CLKXOR2X1 mul_34_8_g884(.A (mul_34_8_n_69), .B (mul_34_8_n_81), .Y
       (out1[2]));
  NOR2X1 mul_34_8_g885(.A (mul_34_8_n_4), .B (mul_34_8_n_76), .Y
       (mul_34_8_n_8));
  CLKXOR2X1 mul_34_8_g886(.A (mul_34_8_n_82), .B (mul_34_8_n_95), .Y
       (out1[3]));
  NAND2BX1 mul_34_8_g887(.AN (mul_34_8_n_73), .B (mul_34_8_n_103), .Y
       (mul_34_8_n_6));
  NAND2BX1 mul_34_8_g888(.AN (mul_34_8_n_66), .B (mul_34_8_n_60), .Y
       (mul_34_8_n_5));
  NAND2BX1 mul_34_8_g889(.AN (mul_34_8_n_62), .B (mul_34_8_n_54), .Y
       (mul_34_8_n_4));
  NOR2BX1 mul_34_8_g890(.AN (mul_34_8_n_33), .B (n_181), .Y
       (mul_34_8_n_3));
  CLKXOR2X1 mul_34_8_g892(.A (in2[5]), .B (in1[1]), .Y (mul_34_8_n_1));
  MX2X1 g2(.A (n_173), .B (in1[1]), .S0 (in2[1]), .Y (n_125));
  MX2XL g894(.A (in1[1]), .B (n_172), .S0 (in2[7]), .Y (n_126));
  CLKINVX1 fopt(.A (n_128), .Y (n_127));
  CLKINVX1 fopt895(.A (n_128), .Y (n_129));
  CLKINVX1 fopt896(.A (mul_34_8_n_87), .Y (n_128));
  CLKINVX1 fopt917(.A (n_159), .Y (n_158));
  CLKINVX1 fopt918(.A (n_161), .Y (n_160));
  CLKINVX1 fopt919(.A (n_159), .Y (n_161));
  BUFX3 fopt920(.A (n_164), .Y (n_163));
  CLKINVX1 fopt921(.A (n_167), .Y (n_166));
  CLKINVX1 fopt922(.A (n_168), .Y (n_167));
  BUFX3 fopt923(.A (n_169), .Y (n_168));
  CLKINVX1 fopt924(.A (n_170), .Y (n_169));
  CLKINVX1 fopt925(.A (in1[1]), .Y (n_170));
  CLKINVX1 fopt926(.A (in1[1]), .Y (n_172));
  CLKINVX1 fopt927(.A (in1[1]), .Y (n_173));
  CLKINVX4 fopt928(.A (in1[1]), .Y (n_175));
  CLKINVX6 fopt929(.A (in1[1]), .Y (n_176));
  CLKINVX1 fopt930(.A (n_181), .Y (n_180));
  CLKINVX1 fopt931(.A (n_182), .Y (n_181));
  CLKINVX1 fopt932(.A (n_182), .Y (n_184));
  CLKINVX1 fopt933(.A (n_182), .Y (n_185));
  BUFX3 fopt934(.A (in1[0]), .Y (n_182));
  CLKINVX3 fopt935(.A (in1[0]), .Y (n_187));
endmodule


