`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Not_1U_1_4(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  INVX1 g2(.A (in1), .Y (out1));
endmodule


