`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Mul2i7u8_4(in1, out1);
  input [7:0] in1;
  output [7:0] out1;
  wire [7:0] in1;
  wire [7:0] out1;
  wire const_mul_32_8_n_1, const_mul_32_8_n_2, const_mul_32_8_n_3,
       const_mul_32_8_n_4, const_mul_32_8_n_5, const_mul_32_8_n_7,
       const_mul_32_8_n_8, const_mul_32_8_n_10;
  wire const_mul_32_8_n_11, const_mul_32_8_n_13, const_mul_32_8_n_14,
       const_mul_32_8_n_16, const_mul_32_8_n_17, const_mul_32_8_n_19,
       const_mul_32_8_n_20;
  assign out1[0] = in1[0];
  XNOR2X1 const_mul_32_8_g151(.A (const_mul_32_8_n_7), .B
       (const_mul_32_8_n_19), .Y (out1[7]));
  INVX1 const_mul_32_8_g152(.A (const_mul_32_8_n_20), .Y (out1[6]));
  ADDFX1 const_mul_32_8_g153(.A (const_mul_32_8_n_16), .B (in1[6]), .CI
       (const_mul_32_8_n_1), .CO (const_mul_32_8_n_19), .S
       (const_mul_32_8_n_20));
  INVX1 const_mul_32_8_g154(.A (const_mul_32_8_n_17), .Y (out1[5]));
  ADDFX1 const_mul_32_8_g155(.A (const_mul_32_8_n_13), .B (in1[5]), .CI
       (const_mul_32_8_n_2), .CO (const_mul_32_8_n_16), .S
       (const_mul_32_8_n_17));
  INVX1 const_mul_32_8_g156(.A (const_mul_32_8_n_14), .Y (out1[4]));
  ADDFX1 const_mul_32_8_g157(.A (const_mul_32_8_n_10), .B (in1[4]), .CI
       (const_mul_32_8_n_4), .CO (const_mul_32_8_n_13), .S
       (const_mul_32_8_n_14));
  INVX1 const_mul_32_8_g158(.A (const_mul_32_8_n_11), .Y (out1[3]));
  ADDFX1 const_mul_32_8_g159(.A (const_mul_32_8_n_8), .B (in1[3]), .CI
       (const_mul_32_8_n_3), .CO (const_mul_32_8_n_10), .S
       (const_mul_32_8_n_11));
  MXI2XL const_mul_32_8_g160(.A (in1[2]), .B (const_mul_32_8_n_2), .S0
       (const_mul_32_8_n_5), .Y (out1[2]));
  NAND2X1 const_mul_32_8_g161(.A (const_mul_32_8_n_2), .B
       (const_mul_32_8_n_5), .Y (const_mul_32_8_n_8));
  XNOR2X1 const_mul_32_8_g162(.A (in1[7]), .B (in1[4]), .Y
       (const_mul_32_8_n_7));
  OAI22X1 const_mul_32_8_g163(.A0 (const_mul_32_8_n_4), .A1 (in1[0]),
       .B0 (const_mul_32_8_n_3), .B1 (in1[1]), .Y (out1[1]));
  NOR2X1 const_mul_32_8_g164(.A (in1[1]), .B (in1[0]), .Y
       (const_mul_32_8_n_5));
  INVX1 const_mul_32_8_g165(.A (in1[1]), .Y (const_mul_32_8_n_4));
  INVX1 const_mul_32_8_g166(.A (in1[0]), .Y (const_mul_32_8_n_3));
  INVX1 const_mul_32_8_g167(.A (in1[2]), .Y (const_mul_32_8_n_2));
  INVX1 const_mul_32_8_g168(.A (in1[3]), .Y (const_mul_32_8_n_1));
endmodule


