`timescale 1ps / 1ps

// Generated by Cadence Encounter(R) RTL Compiler RC14.11 - v14.10-s012_1

module RAM_Mul2i7u9_4(in1, out1);
  input [8:0] in1;
  output [8:0] out1;
  wire [8:0] in1;
  wire [8:0] out1;
  wire const_mul_32_8_n_1, const_mul_32_8_n_2, const_mul_32_8_n_3,
       const_mul_32_8_n_4, const_mul_32_8_n_5, const_mul_32_8_n_6,
       const_mul_32_8_n_8, const_mul_32_8_n_9;
  wire const_mul_32_8_n_11, const_mul_32_8_n_12, const_mul_32_8_n_14,
       const_mul_32_8_n_15, const_mul_32_8_n_17, const_mul_32_8_n_18,
       const_mul_32_8_n_20, const_mul_32_8_n_21;
  wire const_mul_32_8_n_23, const_mul_32_8_n_24;
  assign out1[0] = in1[0];
  XNOR2X1 const_mul_32_8_g175(.A (const_mul_32_8_n_8), .B
       (const_mul_32_8_n_23), .Y (out1[8]));
  INVX1 const_mul_32_8_g176(.A (const_mul_32_8_n_24), .Y (out1[7]));
  ADDFX1 const_mul_32_8_g177(.A (const_mul_32_8_n_20), .B (in1[7]), .CI
       (const_mul_32_8_n_5), .CO (const_mul_32_8_n_23), .S
       (const_mul_32_8_n_24));
  INVX1 const_mul_32_8_g178(.A (const_mul_32_8_n_21), .Y (out1[6]));
  ADDFX1 const_mul_32_8_g179(.A (const_mul_32_8_n_17), .B (in1[6]), .CI
       (const_mul_32_8_n_2), .CO (const_mul_32_8_n_20), .S
       (const_mul_32_8_n_21));
  INVX1 const_mul_32_8_g180(.A (const_mul_32_8_n_18), .Y (out1[5]));
  ADDFX1 const_mul_32_8_g181(.A (const_mul_32_8_n_14), .B (in1[5]), .CI
       (const_mul_32_8_n_3), .CO (const_mul_32_8_n_17), .S
       (const_mul_32_8_n_18));
  INVX1 const_mul_32_8_g182(.A (const_mul_32_8_n_15), .Y (out1[4]));
  ADDFX1 const_mul_32_8_g183(.A (const_mul_32_8_n_11), .B (in1[4]), .CI
       (const_mul_32_8_n_4), .CO (const_mul_32_8_n_14), .S
       (const_mul_32_8_n_15));
  INVX1 const_mul_32_8_g184(.A (const_mul_32_8_n_12), .Y (out1[3]));
  ADDFX1 const_mul_32_8_g185(.A (const_mul_32_8_n_9), .B (in1[3]), .CI
       (const_mul_32_8_n_1), .CO (const_mul_32_8_n_11), .S
       (const_mul_32_8_n_12));
  MXI2XL const_mul_32_8_g186(.A (in1[2]), .B (const_mul_32_8_n_3), .S0
       (const_mul_32_8_n_6), .Y (out1[2]));
  NAND2X1 const_mul_32_8_g187(.A (const_mul_32_8_n_3), .B
       (const_mul_32_8_n_6), .Y (const_mul_32_8_n_9));
  XNOR2X1 const_mul_32_8_g188(.A (in1[8]), .B (in1[5]), .Y
       (const_mul_32_8_n_8));
  OAI22X1 const_mul_32_8_g189(.A0 (const_mul_32_8_n_4), .A1 (in1[0]),
       .B0 (const_mul_32_8_n_1), .B1 (in1[1]), .Y (out1[1]));
  NOR2X1 const_mul_32_8_g190(.A (in1[1]), .B (in1[0]), .Y
       (const_mul_32_8_n_6));
  INVX1 const_mul_32_8_g191(.A (in1[4]), .Y (const_mul_32_8_n_5));
  INVX1 const_mul_32_8_g192(.A (in1[1]), .Y (const_mul_32_8_n_4));
  INVX1 const_mul_32_8_g193(.A (in1[2]), .Y (const_mul_32_8_n_3));
  INVX1 const_mul_32_8_g194(.A (in1[3]), .Y (const_mul_32_8_n_2));
  INVX1 const_mul_32_8_g195(.A (in1[0]), .Y (const_mul_32_8_n_1));
endmodule


