// Generated by stratus_vlg 15.21-p100  (11111646)
// Tue Aug  2 13:41:16 2016
// from c_parts/digitrec_RAM_1800X49_1.cc

`timescale 1ps / 1ps

      
// Generated by stratus_hls 15.21-p100  (11111647)
// Tue Aug  2 13:40:55 2016
// from digitrec_rocc_multimem.cc
/* Include declarations of instantiated parts. */
/* Declaration of the synthesized module. */
module digitrec_RAM_1800X49_1(DIN, CE, RW, in1, out1, clk);

      input [48:0] DIN;
      input CE;
      input RW;
      input [10:0] in1;
      input clk;
      output [48:0] out1;
      reg [48:0] out1;
      reg[48:0] mem[1799:0];

         // Generated by stratus_hls 15.21-p100  (11111647)
         // Tue Aug  2 13:40:55 2016
         // from digitrec_rocc_multimem.cc
         always @(posedge clk)
          begin :thread_119
            if (in1 < 11'd1800) begin
               if (CE) begin
                  if (RW) begin
                     mem[in1] = DIN;
                  end
                  else begin
                     out1 <= mem[in1];
                  end
               end
               else begin
                  out1 <= 49'd000000000000000;
               end
            end
         end


endmodule

